#!/usr/bin/env node
// Auto-generated startup migration — creates missing tables safely (idempotent)
'use strict';
const { Client } = require('pg');

const STATEMENTS = [
  "CREATE TABLE IF NOT EXISTS \"ab_tests\" (\n\t\"id\" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,\n\t\"tenant_id\" uuid NOT NULL,\n\t\"name\" text NOT NULL,\n\t\"hypothesis\" text,\n\t\"status\" text DEFAULT 'draft',\n\t\"type\" text DEFAULT 'email',\n\t\"variants\" jsonb DEFAULT '[]'::jsonb,\n\t\"winner_variant_id\" text,\n\t\"started_at\" timestamp,\n\t\"ended_at\" timestamp,\n\t\"significance\" numeric(6, 4),\n\t\"created_at\" timestamp DEFAULT now(),\n\t\"updated_at\" timestamp DEFAULT now()\n);",
  "CREATE TABLE IF NOT EXISTS \"accounts\" (\n\t\"id\" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,\n\t\"tenant_id\" uuid NOT NULL,\n\t\"name\" text NOT NULL,\n\t\"website\" text,\n\t\"industry\" text,\n\t\"size\" text,\n\t\"revenue\" numeric(15, 2),\n\t\"phone\" text,\n\t\"email\" text,\n\t\"address\" text,\n\t\"city\" text,\n\t\"country\" text,\n\t\"logo\" text,\n\t\"status\" text DEFAULT 'active',\n\t\"notes\" text,\n\t\"tags\" jsonb DEFAULT '[]'::jsonb,\n\t\"assigned_to\" uuid,\n\t\"created_by\" uuid,\n\t\"created_at\" timestamp DEFAULT now(),\n\t\"updated_at\" timestamp DEFAULT now()\n);",
  "CREATE TABLE IF NOT EXISTS \"activities\" (\n\t\"id\" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,\n\t\"tenant_id\" uuid NOT NULL,\n\t\"type\" text NOT NULL,\n\t\"title\" text NOT NULL,\n\t\"description\" text,\n\t\"contact_id\" uuid,\n\t\"deal_id\" uuid,\n\t\"lead_id\" uuid,\n\t\"account_id\" uuid,\n\t\"created_by\" uuid,\n\t\"scheduled_at\" timestamp,\n\t\"completed_at\" timestamp,\n\t\"created_at\" timestamp DEFAULT now()\n);",
  "CREATE TABLE IF NOT EXISTS \"agent_lead_gen_results\" (\n\t\"id\" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,\n\t\"tenant_id\" uuid NOT NULL,\n\t\"session_id\" uuid,\n\t\"first_name\" text,\n\t\"last_name\" text,\n\t\"email\" text,\n\t\"company\" text,\n\t\"job_title\" text,\n\t\"phone\" text,\n\t\"source\" text,\n\t\"score\" integer DEFAULT 0,\n\t\"enrichment_data\" jsonb DEFAULT '{}'::jsonb,\n\t\"outreach_status\" text DEFAULT 'pending',\n\t\"imported_as_lead_id\" uuid,\n\t\"created_at\" timestamp DEFAULT now()\n);",
  "CREATE TABLE IF NOT EXISTS \"agent_memories\" (\n\t\"id\" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,\n\t\"tenant_id\" uuid NOT NULL,\n\t\"agent_type\" text NOT NULL,\n\t\"category\" text NOT NULL,\n\t\"key\" text NOT NULL,\n\t\"value\" text NOT NULL,\n\t\"importance\" integer DEFAULT 5,\n\t\"source\" text,\n\t\"related_entity_id\" uuid,\n\t\"related_entity_type\" text,\n\t\"expires_at\" timestamp,\n\t\"usage_count\" integer DEFAULT 0,\n\t\"last_used_at\" timestamp,\n\t\"created_at\" timestamp DEFAULT now(),\n\t\"updated_at\" timestamp DEFAULT now()\n);",
  "CREATE TABLE IF NOT EXISTS \"agent_messages\" (\n\t\"id\" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,\n\t\"session_id\" uuid NOT NULL,\n\t\"tenant_id\" uuid NOT NULL,\n\t\"role\" text NOT NULL,\n\t\"content\" text NOT NULL,\n\t\"tokens_used\" integer DEFAULT 0,\n\t\"tool_calls\" jsonb DEFAULT '[]'::jsonb,\n\t\"memories_used\" jsonb DEFAULT '[]'::jsonb,\n\t\"memories_created\" jsonb DEFAULT '[]'::jsonb,\n\t\"created_at\" timestamp DEFAULT now()\n);",
  "CREATE TABLE IF NOT EXISTS \"agent_sessions\" (\n\t\"id\" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,\n\t\"tenant_id\" uuid NOT NULL,\n\t\"user_id\" uuid NOT NULL,\n\t\"agent_type\" text NOT NULL,\n\t\"title\" text,\n\t\"summary\" text,\n\t\"message_count\" integer DEFAULT 0,\n\t\"tokens_used\" integer DEFAULT 0,\n\t\"is_active\" boolean DEFAULT true,\n\t\"created_at\" timestamp DEFAULT now(),\n\t\"updated_at\" timestamp DEFAULT now()\n);",
  "CREATE TABLE IF NOT EXISTS \"agent_tasks\" (\n\t\"id\" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,\n\t\"tenant_id\" uuid NOT NULL,\n\t\"agent_type\" text NOT NULL,\n\t\"session_id\" uuid,\n\t\"title\" text NOT NULL,\n\t\"description\" text,\n\t\"status\" text DEFAULT 'pending',\n\t\"priority\" text DEFAULT 'medium',\n\t\"result\" text,\n\t\"assigned_to_user_id\" uuid,\n\t\"due_at\" timestamp,\n\t\"completed_at\" timestamp,\n\t\"created_at\" timestamp DEFAULT now(),\n\t\"updated_at\" timestamp DEFAULT now()\n);",
  "CREATE TABLE IF NOT EXISTS \"agents\" (\n\t\"id\" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,\n\t\"tenant_id\" uuid NOT NULL,\n\t\"type\" text NOT NULL,\n\t\"name\" text NOT NULL,\n\t\"is_active\" boolean DEFAULT true,\n\t\"personality\" text,\n\t\"total_sessions\" integer DEFAULT 0,\n\t\"total_messages\" integer DEFAULT 0,\n\t\"last_active_at\" timestamp,\n\t\"created_at\" timestamp DEFAULT now()\n);",
  "CREATE TABLE IF NOT EXISTS \"ai_usage\" (\n\t\"id\" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,\n\t\"tenant_id\" uuid NOT NULL,\n\t\"user_id\" uuid,\n\t\"type\" text NOT NULL,\n\t\"tokens\" integer DEFAULT 0,\n\t\"cost\" numeric(8, 6) DEFAULT '0',\n\t\"created_at\" timestamp DEFAULT now()\n);",
  "CREATE TABLE IF NOT EXISTS \"backlinks\" (\n\t\"id\" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,\n\t\"tenant_id\" uuid NOT NULL,\n\t\"project_id\" uuid,\n\t\"source_url\" text NOT NULL,\n\t\"source_domain\" text,\n\t\"target_url\" text NOT NULL,\n\t\"anchor_text\" text,\n\t\"domain_authority\" integer DEFAULT 0,\n\t\"page_authority\" integer DEFAULT 0,\n\t\"is_do_follow\" boolean DEFAULT true,\n\t\"is_active\" boolean DEFAULT true,\n\t\"first_seen\" timestamp DEFAULT now(),\n\t\"last_seen\" timestamp DEFAULT now(),\n\t\"created_at\" timestamp DEFAULT now()\n);",
  "CREATE TABLE IF NOT EXISTS \"bank_accounts\" (\n\t\"id\" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,\n\t\"tenant_id\" uuid NOT NULL,\n\t\"name\" text NOT NULL,\n\t\"type\" text DEFAULT 'checking',\n\t\"currency\" text DEFAULT 'USD',\n\t\"balance\" numeric(15, 2) DEFAULT '0',\n\t\"institution\" text,\n\t\"account_number\" text,\n\t\"is_active\" boolean DEFAULT true,\n\t\"last_sync_at\" timestamp,\n\t\"created_at\" timestamp DEFAULT now()\n);",
  "CREATE TABLE IF NOT EXISTS \"campaigns\" (\n\t\"id\" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,\n\t\"tenant_id\" uuid NOT NULL,\n\t\"name\" text NOT NULL,\n\t\"subject\" text,\n\t\"type\" text DEFAULT 'email',\n\t\"status\" text DEFAULT 'draft',\n\t\"content\" text,\n\t\"scheduled_at\" timestamp,\n\t\"sent_at\" timestamp,\n\t\"recipient_count\" integer DEFAULT 0,\n\t\"open_count\" integer DEFAULT 0,\n\t\"click_count\" integer DEFAULT 0,\n\t\"reply_count\" integer DEFAULT 0,\n\t\"created_by\" uuid,\n\t\"created_at\" timestamp DEFAULT now(),\n\t\"updated_at\" timestamp DEFAULT now()\n);",
  "CREATE TABLE IF NOT EXISTS \"client_portal_access\" (\n\t\"id\" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,\n\t\"tenant_id\" uuid NOT NULL,\n\t\"contact_id\" uuid,\n\t\"email\" text NOT NULL,\n\t\"access_token\" text,\n\t\"permissions\" jsonb DEFAULT '[\"view_projects\",\"view_invoices\"]'::jsonb,\n\t\"last_login_at\" timestamp,\n\t\"is_active\" boolean DEFAULT true,\n\t\"created_at\" timestamp DEFAULT now()\n);",
  "CREATE TABLE IF NOT EXISTS \"companies\" (\n\t\"id\" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,\n\t\"tenant_id\" uuid NOT NULL,\n\t\"name\" text NOT NULL,\n\t\"domain\" text,\n\t\"website\" text,\n\t\"industry\" text,\n\t\"sub_industry\" text,\n\t\"size\" text,\n\t\"employee_count\" integer,\n\t\"revenue\" text,\n\t\"founded\" integer,\n\t\"hq_city\" text,\n\t\"hq_state\" text,\n\t\"hq_country\" text,\n\t\"description\" text,\n\t\"linkedin_url\" text,\n\t\"twitter_url\" text,\n\t\"crunchbase_url\" text,\n\t\"tech_stack\" jsonb DEFAULT '[]'::jsonb,\n\t\"keywords\" jsonb DEFAULT '[]'::jsonb,\n\t\"funding_stage\" text,\n\t\"total_funding\" text,\n\t\"last_funding_date\" text,\n\t\"intent_signals\" jsonb DEFAULT '[]'::jsonb,\n\t\"score\" integer DEFAULT 0,\n\t\"tags\" jsonb DEFAULT '[]'::jsonb,\n\t\"data_source\" text DEFAULT 'enriched',\n\t\"last_enriched_at\" timestamp,\n\t\"created_at\" timestamp DEFAULT now(),\n\t\"updated_at\" timestamp DEFAULT now()\n);",
  "CREATE TABLE IF NOT EXISTS \"contacts\" (\n\t\"id\" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,\n\t\"tenant_id\" uuid NOT NULL,\n\t\"first_name\" text NOT NULL,\n\t\"last_name\" text,\n\t\"email\" text,\n\t\"phone\" text,\n\t\"company\" text,\n\t\"job_title\" text,\n\t\"website\" text,\n\t\"linkedin\" text,\n\t\"address\" text,\n\t\"city\" text,\n\t\"country\" text,\n\t\"avatar\" text,\n\t\"status\" text DEFAULT 'active',\n\t\"source\" text,\n\t\"tags\" jsonb DEFAULT '[]'::jsonb,\n\t\"custom_fields\" jsonb DEFAULT '{}'::jsonb,\n\t\"notes\" text,\n\t\"assigned_to\" uuid,\n\t\"last_contacted_at\" timestamp,\n\t\"created_by\" uuid,\n\t\"created_at\" timestamp DEFAULT now(),\n\t\"updated_at\" timestamp DEFAULT now()\n);",
  "CREATE TABLE IF NOT EXISTS \"content_ideas\" (\n\t\"id\" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,\n\t\"tenant_id\" uuid NOT NULL,\n\t\"project_id\" uuid,\n\t\"title\" text NOT NULL,\n\t\"keyword\" text,\n\t\"search_volume\" integer DEFAULT 0,\n\t\"difficulty\" integer DEFAULT 0,\n\t\"content_type\" text DEFAULT 'blog',\n\t\"outline\" jsonb DEFAULT '[]'::jsonb,\n\t\"status\" text DEFAULT 'idea',\n\t\"created_at\" timestamp DEFAULT now()\n);",
  "CREATE TABLE IF NOT EXISTS \"deals\" (\n\t\"id\" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,\n\t\"tenant_id\" uuid NOT NULL,\n\t\"pipeline_id\" uuid,\n\t\"contact_id\" uuid,\n\t\"title\" text NOT NULL,\n\t\"stage\" text DEFAULT 'prospecting' NOT NULL,\n\t\"value\" numeric(12, 2) DEFAULT '0',\n\t\"currency\" text DEFAULT 'USD',\n\t\"probability\" integer DEFAULT 0,\n\t\"expected_close_date\" timestamp,\n\t\"closed_at\" timestamp,\n\t\"notes\" text,\n\t\"tags\" jsonb DEFAULT '[]'::jsonb,\n\t\"assigned_to\" uuid,\n\t\"created_by\" uuid,\n\t\"created_at\" timestamp DEFAULT now(),\n\t\"updated_at\" timestamp DEFAULT now()\n);",
  "CREATE TABLE IF NOT EXISTS \"documents\" (\n\t\"id\" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,\n\t\"tenant_id\" uuid NOT NULL,\n\t\"name\" text NOT NULL,\n\t\"type\" text DEFAULT 'file',\n\t\"mime_type\" text,\n\t\"size\" integer DEFAULT 0,\n\t\"url\" text,\n\t\"content\" text,\n\t\"parent_id\" uuid,\n\t\"tags\" jsonb DEFAULT '[]'::jsonb,\n\t\"shared_with\" jsonb DEFAULT '[]'::jsonb,\n\t\"uploaded_by\" uuid,\n\t\"created_at\" timestamp DEFAULT now(),\n\t\"updated_at\" timestamp DEFAULT now()\n);",
  "CREATE TABLE IF NOT EXISTS \"employees\" (\n\t\"id\" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,\n\t\"tenant_id\" uuid NOT NULL,\n\t\"user_id\" uuid,\n\t\"first_name\" text NOT NULL,\n\t\"last_name\" text,\n\t\"email\" text,\n\t\"phone\" text,\n\t\"avatar\" text,\n\t\"department\" text,\n\t\"job_title\" text,\n\t\"employment_type\" text DEFAULT 'full_time',\n\t\"status\" text DEFAULT 'active',\n\t\"start_date\" timestamp,\n\t\"end_date\" timestamp,\n\t\"salary\" numeric(12, 2),\n\t\"currency\" text DEFAULT 'USD',\n\t\"manager_id\" uuid,\n\t\"skills\" jsonb DEFAULT '[]'::jsonb,\n\t\"location\" text,\n\t\"timezone\" text,\n\t\"created_at\" timestamp DEFAULT now(),\n\t\"updated_at\" timestamp DEFAULT now()\n);",
  "CREATE TABLE IF NOT EXISTS \"error_logs\" (\n\t\"id\" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,\n\t\"tenant_id\" uuid,\n\t\"severity\" text NOT NULL,\n\t\"category\" text NOT NULL,\n\t\"message\" text NOT NULL,\n\t\"stack\" text,\n\t\"context\" jsonb DEFAULT '{}'::jsonb,\n\t\"user_id\" uuid,\n\t\"endpoint\" text,\n\t\"resolved\" boolean DEFAULT false,\n\t\"resolved_at\" timestamp,\n\t\"resolved_by\" text,\n\t\"healing_attempts\" integer DEFAULT 0,\n\t\"healing_log\" jsonb DEFAULT '[]'::jsonb,\n\t\"created_at\" timestamp DEFAULT now()\n);",
  "CREATE TABLE IF NOT EXISTS \"funnels\" (\n\t\"id\" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,\n\t\"tenant_id\" uuid NOT NULL,\n\t\"name\" text NOT NULL,\n\t\"description\" text,\n\t\"offer\" text,\n\t\"target_audience\" text,\n\t\"status\" text DEFAULT 'draft',\n\t\"steps\" jsonb DEFAULT '[]'::jsonb,\n\t\"email_sequence\" jsonb DEFAULT '[]'::jsonb,\n\t\"ad_copy\" jsonb DEFAULT '[]'::jsonb,\n\t\"landing_page_id\" uuid,\n\t\"total_leads\" integer DEFAULT 0,\n\t\"total_conversions\" integer DEFAULT 0,\n\t\"created_at\" timestamp DEFAULT now(),\n\t\"updated_at\" timestamp DEFAULT now()\n);",
  "CREATE TABLE IF NOT EXISTS \"healing_rules\" (\n\t\"id\" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,\n\t\"name\" text NOT NULL,\n\t\"description\" text,\n\t\"trigger\" text NOT NULL,\n\t\"pattern\" text NOT NULL,\n\t\"category\" text NOT NULL,\n\t\"action\" text NOT NULL,\n\t\"action_config\" jsonb DEFAULT '{}'::jsonb,\n\t\"is_active\" boolean DEFAULT true,\n\t\"success_count\" integer DEFAULT 0,\n\t\"failure_count\" integer DEFAULT 0,\n\t\"last_triggered_at\" timestamp,\n\t\"created_at\" timestamp DEFAULT now()\n);",
  "CREATE TABLE IF NOT EXISTS \"health_checks\" (\n\t\"id\" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,\n\t\"check_type\" text NOT NULL,\n\t\"status\" text NOT NULL,\n\t\"latency_ms\" integer,\n\t\"message\" text,\n\t\"details\" jsonb DEFAULT '{}'::jsonb,\n\t\"checked_at\" timestamp DEFAULT now()\n);",
  "CREATE TABLE IF NOT EXISTS \"intent_signals\" (\n\t\"id\" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,\n\t\"tenant_id\" uuid NOT NULL,\n\t\"company_domain\" text,\n\t\"company_name\" text,\n\t\"topic\" text NOT NULL,\n\t\"signal_type\" text NOT NULL,\n\t\"strength\" integer DEFAULT 50,\n\t\"description\" text,\n\t\"source_url\" text,\n\t\"detected_at\" timestamp DEFAULT now(),\n\t\"expires_at\" timestamp\n);",
  "CREATE TABLE IF NOT EXISTS \"invoices\" (\n\t\"id\" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,\n\t\"tenant_id\" uuid NOT NULL,\n\t\"number\" text NOT NULL,\n\t\"contact_id\" uuid,\n\t\"account_id\" uuid,\n\t\"deal_id\" uuid,\n\t\"status\" text DEFAULT 'draft',\n\t\"subtotal\" numeric(12, 2) DEFAULT '0',\n\t\"tax\" numeric(12, 2) DEFAULT '0',\n\t\"total\" numeric(12, 2) DEFAULT '0',\n\t\"currency\" text DEFAULT 'USD',\n\t\"due_date\" timestamp,\n\t\"paid_at\" timestamp,\n\t\"notes\" text,\n\t\"items\" jsonb DEFAULT '[]'::jsonb,\n\t\"created_by\" uuid,\n\t\"created_at\" timestamp DEFAULT now(),\n\t\"updated_at\" timestamp DEFAULT now()\n);",
  "CREATE TABLE IF NOT EXISTS \"keywords\" (\n\t\"id\" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,\n\t\"tenant_id\" uuid NOT NULL,\n\t\"project_id\" uuid,\n\t\"keyword\" text NOT NULL,\n\t\"search_volume\" integer DEFAULT 0,\n\t\"difficulty\" integer DEFAULT 0,\n\t\"cpc\" numeric(8, 2) DEFAULT '0',\n\t\"current_rank\" integer,\n\t\"previous_rank\" integer,\n\t\"url\" text,\n\t\"intent\" text,\n\t\"country\" text DEFAULT 'US',\n\t\"tags\" jsonb DEFAULT '[]'::jsonb,\n\t\"created_at\" timestamp DEFAULT now(),\n\t\"updated_at\" timestamp DEFAULT now()\n);",
  "CREATE TABLE IF NOT EXISTS \"landing_pages\" (\n\t\"id\" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,\n\t\"tenant_id\" uuid NOT NULL,\n\t\"name\" text NOT NULL,\n\t\"slug\" text NOT NULL,\n\t\"title\" text,\n\t\"description\" text,\n\t\"template\" text DEFAULT 'blank',\n\t\"blocks\" jsonb DEFAULT '[]'::jsonb,\n\t\"seo_title\" text,\n\t\"seo_description\" text,\n\t\"is_published\" boolean DEFAULT false,\n\t\"published_at\" timestamp,\n\t\"views\" integer DEFAULT 0,\n\t\"conversions\" integer DEFAULT 0,\n\t\"created_by\" uuid,\n\t\"created_at\" timestamp DEFAULT now(),\n\t\"updated_at\" timestamp DEFAULT now()\n);",
  "CREATE TABLE IF NOT EXISTS \"leads\" (\n\t\"id\" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,\n\t\"tenant_id\" uuid NOT NULL,\n\t\"first_name\" text NOT NULL,\n\t\"last_name\" text,\n\t\"email\" text,\n\t\"phone\" text,\n\t\"company\" text,\n\t\"job_title\" text,\n\t\"source\" text,\n\t\"status\" text DEFAULT 'new',\n\t\"score\" integer DEFAULT 0,\n\t\"estimated_value\" numeric(12, 2),\n\t\"notes\" text,\n\t\"tags\" jsonb DEFAULT '[]'::jsonb,\n\t\"assigned_to\" uuid,\n\t\"converted_to_contact_id\" uuid,\n\t\"created_by\" uuid,\n\t\"created_at\" timestamp DEFAULT now(),\n\t\"updated_at\" timestamp DEFAULT now()\n);",
  "CREATE TABLE IF NOT EXISTS \"orders\" (\n\t\"id\" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,\n\t\"tenant_id\" uuid NOT NULL,\n\t\"store_id\" uuid,\n\t\"order_number\" text NOT NULL,\n\t\"status\" text DEFAULT 'pending',\n\t\"customer_name\" text,\n\t\"customer_email\" text,\n\t\"customer_phone\" text,\n\t\"shipping_address\" jsonb DEFAULT '{}'::jsonb,\n\t\"items\" jsonb DEFAULT '[]'::jsonb,\n\t\"subtotal\" numeric(12, 2) DEFAULT '0',\n\t\"tax\" numeric(12, 2) DEFAULT '0',\n\t\"shipping\" numeric(12, 2) DEFAULT '0',\n\t\"total\" numeric(12, 2) DEFAULT '0',\n\t\"currency\" text DEFAULT 'USD',\n\t\"payment_status\" text DEFAULT 'unpaid',\n\t\"payment_method\" text,\n\t\"notes\" text,\n\t\"created_at\" timestamp DEFAULT now(),\n\t\"updated_at\" timestamp DEFAULT now()\n);",
  "CREATE TABLE IF NOT EXISTS \"performance_metrics\" (\n\t\"id\" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,\n\t\"metric_type\" text NOT NULL,\n\t\"value\" numeric(10, 4) NOT NULL,\n\t\"unit\" text,\n\t\"endpoint\" text,\n\t\"tags\" jsonb DEFAULT '{}'::jsonb,\n\t\"recorded_at\" timestamp DEFAULT now()\n);",
  "CREATE TABLE IF NOT EXISTS \"pipelines\" (\n\t\"id\" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,\n\t\"tenant_id\" uuid NOT NULL,\n\t\"name\" text NOT NULL,\n\t\"stages\" jsonb DEFAULT '[]'::jsonb,\n\t\"is_default\" boolean DEFAULT false,\n\t\"created_at\" timestamp DEFAULT now()\n);",
  "CREATE TABLE IF NOT EXISTS \"products\" (\n\t\"id\" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,\n\t\"tenant_id\" uuid NOT NULL,\n\t\"store_id\" uuid,\n\t\"name\" text NOT NULL,\n\t\"slug\" text,\n\t\"description\" text,\n\t\"short_description\" text,\n\t\"sku\" text,\n\t\"barcode\" text,\n\t\"price\" numeric(12, 2) DEFAULT '0' NOT NULL,\n\t\"compare_at_price\" numeric(12, 2),\n\t\"cost\" numeric(12, 2),\n\t\"currency\" text DEFAULT 'USD',\n\t\"category\" text,\n\t\"tags\" jsonb DEFAULT '[]'::jsonb,\n\t\"images\" jsonb DEFAULT '[]'::jsonb,\n\t\"weight\" numeric(8, 2),\n\t\"dimensions\" jsonb DEFAULT '{}'::jsonb,\n\t\"inventory\" integer DEFAULT 0,\n\t\"low_stock_threshold\" integer DEFAULT 10,\n\t\"track_inventory\" boolean DEFAULT true,\n\t\"is_available\" boolean DEFAULT true,\n\t\"is_featured\" boolean DEFAULT false,\n\t\"ai_score\" integer DEFAULT 0,\n\t\"attributes\" jsonb DEFAULT '{}'::jsonb,\n\t\"created_at\" timestamp DEFAULT now(),\n\t\"updated_at\" timestamp DEFAULT now()\n);",
  "CREATE TABLE IF NOT EXISTS \"project_tasks\" (\n\t\"id\" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,\n\t\"tenant_id\" uuid NOT NULL,\n\t\"project_id\" uuid NOT NULL,\n\t\"title\" text NOT NULL,\n\t\"description\" text,\n\t\"status\" text DEFAULT 'todo',\n\t\"priority\" text DEFAULT 'medium',\n\t\"assignee_id\" uuid,\n\t\"start_date\" timestamp,\n\t\"due_date\" timestamp,\n\t\"completed_at\" timestamp,\n\t\"estimated_hours\" numeric(6, 2),\n\t\"actual_hours\" numeric(6, 2),\n\t\"parent_id\" uuid,\n\t\"order\" integer DEFAULT 0,\n\t\"dependencies\" jsonb DEFAULT '[]'::jsonb,\n\t\"created_at\" timestamp DEFAULT now(),\n\t\"updated_at\" timestamp DEFAULT now()\n);",
  "CREATE TABLE IF NOT EXISTS \"projects\" (\n\t\"id\" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,\n\t\"tenant_id\" uuid NOT NULL,\n\t\"name\" text NOT NULL,\n\t\"description\" text,\n\t\"status\" text DEFAULT 'planning',\n\t\"priority\" text DEFAULT 'medium',\n\t\"color\" text DEFAULT '#3b82f6',\n\t\"start_date\" timestamp,\n\t\"due_date\" timestamp,\n\t\"completed_at\" timestamp,\n\t\"budget\" numeric(12, 2),\n\t\"progress\" integer DEFAULT 0,\n\t\"owner_id\" uuid,\n\t\"members\" jsonb DEFAULT '[]'::jsonb,\n\t\"tags\" jsonb DEFAULT '[]'::jsonb,\n\t\"deal_id\" uuid,\n\t\"contact_id\" uuid,\n\t\"created_at\" timestamp DEFAULT now(),\n\t\"updated_at\" timestamp DEFAULT now()\n);",
  "CREATE TABLE IF NOT EXISTS \"prospect_lists\" (\n\t\"id\" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,\n\t\"tenant_id\" uuid NOT NULL,\n\t\"name\" text NOT NULL,\n\t\"description\" text,\n\t\"filters\" jsonb DEFAULT '{}'::jsonb,\n\t\"prospect_count\" integer DEFAULT 0,\n\t\"created_by\" uuid,\n\t\"created_at\" timestamp DEFAULT now(),\n\t\"updated_at\" timestamp DEFAULT now()\n);",
  "CREATE TABLE IF NOT EXISTS \"prospects\" (\n\t\"id\" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,\n\t\"tenant_id\" uuid NOT NULL,\n\t\"company_id\" uuid,\n\t\"first_name\" text NOT NULL,\n\t\"last_name\" text,\n\t\"email\" text,\n\t\"email_status\" text DEFAULT 'unknown',\n\t\"work_email\" text,\n\t\"personal_email\" text,\n\t\"phone\" text,\n\t\"direct_phone\" text,\n\t\"mobile_phone\" text,\n\t\"job_title\" text,\n\t\"seniority\" text,\n\t\"department\" text,\n\t\"company\" text,\n\t\"company_domain\" text,\n\t\"linkedin_url\" text,\n\t\"twitter_url\" text,\n\t\"location\" text,\n\t\"city\" text,\n\t\"country\" text,\n\t\"timezone\" text,\n\t\"bio\" text,\n\t\"score\" integer DEFAULT 0,\n\t\"intent_score\" integer DEFAULT 0,\n\t\"buying_signals\" jsonb DEFAULT '[]'::jsonb,\n\t\"tech_stack\" jsonb DEFAULT '[]'::jsonb,\n\t\"skills\" jsonb DEFAULT '[]'::jsonb,\n\t\"tags\" jsonb DEFAULT '[]'::jsonb,\n\t\"outreach_status\" text DEFAULT 'new',\n\t\"last_contacted_at\" timestamp,\n\t\"sequence_id\" uuid,\n\t\"imported_as_lead_id\" uuid,\n\t\"imported_as_contact_id\" uuid,\n\t\"data_source\" text DEFAULT 'enriched',\n\t\"last_enriched_at\" timestamp,\n\t\"verified_at\" timestamp,\n\t\"created_at\" timestamp DEFAULT now(),\n\t\"updated_at\" timestamp DEFAULT now()\n);",
  "CREATE TABLE IF NOT EXISTS \"reputation_reviews\" (\n\t\"id\" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,\n\t\"tenant_id\" uuid NOT NULL,\n\t\"platform\" text NOT NULL,\n\t\"reviewer_name\" text,\n\t\"rating\" integer DEFAULT 5,\n\t\"content\" text,\n\t\"response\" text,\n\t\"sentiment\" text DEFAULT 'positive',\n\t\"url\" text,\n\t\"published_at\" timestamp,\n\t\"responded_at\" timestamp,\n\t\"created_at\" timestamp DEFAULT now()\n);",
  "CREATE TABLE IF NOT EXISTS \"seo_audits\" (\n\t\"id\" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,\n\t\"tenant_id\" uuid NOT NULL,\n\t\"project_id\" uuid,\n\t\"score\" integer DEFAULT 0,\n\t\"issues\" jsonb DEFAULT '[]'::jsonb,\n\t\"summary\" jsonb DEFAULT '{\"critical\":0,\"warnings\":0,\"passed\":0,\"totalPages\":0}'::jsonb,\n\t\"crawled_at\" timestamp DEFAULT now(),\n\t\"created_at\" timestamp DEFAULT now()\n);",
  "CREATE TABLE IF NOT EXISTS \"seo_projects\" (\n\t\"id\" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,\n\t\"tenant_id\" uuid NOT NULL,\n\t\"name\" text NOT NULL,\n\t\"domain\" text NOT NULL,\n\t\"country\" text DEFAULT 'US',\n\t\"language\" text DEFAULT 'en',\n\t\"competitors\" jsonb DEFAULT '[]'::jsonb,\n\t\"is_active\" boolean DEFAULT true,\n\t\"created_at\" timestamp DEFAULT now(),\n\t\"updated_at\" timestamp DEFAULT now()\n);",
  "CREATE TABLE IF NOT EXISTS \"sequences\" (\n\t\"id\" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,\n\t\"tenant_id\" uuid NOT NULL,\n\t\"name\" text NOT NULL,\n\t\"description\" text,\n\t\"status\" text DEFAULT 'draft',\n\t\"steps\" jsonb DEFAULT '[]'::jsonb,\n\t\"total_enrolled\" integer DEFAULT 0,\n\t\"total_replied\" integer DEFAULT 0,\n\t\"total_converted\" integer DEFAULT 0,\n\t\"created_by\" uuid,\n\t\"created_at\" timestamp DEFAULT now(),\n\t\"updated_at\" timestamp DEFAULT now()\n);",
  "CREATE TABLE IF NOT EXISTS \"stores\" (\n\t\"id\" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,\n\t\"tenant_id\" uuid NOT NULL,\n\t\"name\" text NOT NULL,\n\t\"slug\" text,\n\t\"description\" text,\n\t\"logo\" text,\n\t\"banner\" text,\n\t\"currency\" text DEFAULT 'USD',\n\t\"primary_color\" text DEFAULT '#3b82f6',\n\t\"is_published\" boolean DEFAULT false,\n\t\"domain\" text,\n\t\"settings\" jsonb DEFAULT '{}'::jsonb,\n\t\"created_at\" timestamp DEFAULT now(),\n\t\"updated_at\" timestamp DEFAULT now(),\n\tCONSTRAINT \"stores_slug_unique\" UNIQUE(\"slug\")\n);",
  "CREATE TABLE IF NOT EXISTS \"tasks\" (\n\t\"id\" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,\n\t\"tenant_id\" uuid NOT NULL,\n\t\"title\" text NOT NULL,\n\t\"description\" text,\n\t\"status\" text DEFAULT 'todo',\n\t\"priority\" text DEFAULT 'medium',\n\t\"due_date\" timestamp,\n\t\"completed_at\" timestamp,\n\t\"contact_id\" uuid,\n\t\"deal_id\" uuid,\n\t\"assigned_to\" uuid,\n\t\"created_by\" uuid,\n\t\"tags\" jsonb DEFAULT '[]'::jsonb,\n\t\"created_at\" timestamp DEFAULT now(),\n\t\"updated_at\" timestamp DEFAULT now()\n);",
  "CREATE TABLE IF NOT EXISTS \"tax_rates\" (\n\t\"id\" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,\n\t\"tenant_id\" uuid NOT NULL,\n\t\"name\" text NOT NULL,\n\t\"rate\" numeric(6, 4) NOT NULL,\n\t\"country\" text,\n\t\"region\" text,\n\t\"is_default\" boolean DEFAULT false,\n\t\"created_at\" timestamp DEFAULT now()\n);",
  "CREATE TABLE IF NOT EXISTS \"technographics\" (\n\t\"id\" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,\n\t\"tenant_id\" uuid NOT NULL,\n\t\"company_id\" uuid,\n\t\"company_domain\" text,\n\t\"technology\" text NOT NULL,\n\t\"category\" text,\n\t\"vendor\" text,\n\t\"confidence\" integer DEFAULT 80,\n\t\"detected_at\" timestamp DEFAULT now()\n);",
  "CREATE TABLE IF NOT EXISTS \"tenants\" (\n\t\"id\" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,\n\t\"name\" text NOT NULL,\n\t\"domain\" text NOT NULL,\n\t\"slug\" text NOT NULL,\n\t\"logo\" text,\n\t\"primary_color\" text DEFAULT '#3b82f6',\n\t\"subscription_plan\" text DEFAULT 'trial',\n\t\"subscription_status\" text DEFAULT 'trialing',\n\t\"trial_ends_at\" timestamp,\n\t\"max_users\" integer DEFAULT 3,\n\t\"max_contacts\" integer DEFAULT 500,\n\t\"stripe_customer_id\" text,\n\t\"stripe_subscription_id\" text,\n\t\"settings\" jsonb DEFAULT '{}'::jsonb,\n\t\"is_active\" boolean DEFAULT true,\n\t\"created_at\" timestamp DEFAULT now(),\n\t\"updated_at\" timestamp DEFAULT now(),\n\tCONSTRAINT \"tenants_domain_unique\" UNIQUE(\"domain\"),\n\tCONSTRAINT \"tenants_slug_unique\" UNIQUE(\"slug\"),\n\tCONSTRAINT \"tenants_stripe_customer_id_unique\" UNIQUE(\"stripe_customer_id\"),\n\tCONSTRAINT \"tenants_stripe_subscription_id_unique\" UNIQUE(\"stripe_subscription_id\")\n);",
  "CREATE TABLE IF NOT EXISTS \"transactions\" (\n\t\"id\" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,\n\t\"tenant_id\" uuid NOT NULL,\n\t\"type\" text NOT NULL,\n\t\"category\" text,\n\t\"description\" text NOT NULL,\n\t\"amount\" numeric(15, 2) NOT NULL,\n\t\"currency\" text DEFAULT 'USD',\n\t\"exchange_rate\" numeric(10, 6) DEFAULT '1',\n\t\"amount_usd\" numeric(15, 2),\n\t\"date\" timestamp NOT NULL,\n\t\"account_id\" text,\n\t\"contact_id\" uuid,\n\t\"invoice_id\" uuid,\n\t\"tags\" jsonb DEFAULT '[]'::jsonb,\n\t\"reconciled\" boolean DEFAULT false,\n\t\"created_at\" timestamp DEFAULT now()\n);",
  "CREATE TABLE IF NOT EXISTS \"users\" (\n\t\"id\" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,\n\t\"tenant_id\" uuid NOT NULL,\n\t\"email\" text NOT NULL,\n\t\"first_name\" text,\n\t\"last_name\" text,\n\t\"avatar\" text,\n\t\"password_hash\" text NOT NULL,\n\t\"role\" text DEFAULT 'user',\n\t\"permissions\" jsonb DEFAULT '[]'::jsonb,\n\t\"is_active\" boolean DEFAULT true,\n\t\"email_verified\" boolean DEFAULT false,\n\t\"email_verification_token\" text,\n\t\"password_reset_token\" text,\n\t\"password_reset_expires\" timestamp,\n\t\"last_login_at\" timestamp,\n\t\"preferred_language\" text DEFAULT 'en',\n\t\"timezone\" text DEFAULT 'UTC',\n\t\"created_at\" timestamp DEFAULT now(),\n\t\"updated_at\" timestamp DEFAULT now()\n);",
  "CREATE TABLE IF NOT EXISTS \"website_visitors\" (\n\t\"id\" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,\n\t\"tenant_id\" uuid NOT NULL,\n\t\"visitor_id\" text,\n\t\"company_name\" text,\n\t\"company_domain\" text,\n\t\"ip_address\" text,\n\t\"country\" text,\n\t\"city\" text,\n\t\"pages\" jsonb DEFAULT '[]'::jsonb,\n\t\"session_count\" integer DEFAULT 1,\n\t\"total_time_on_site\" integer DEFAULT 0,\n\t\"last_seen\" timestamp DEFAULT now(),\n\t\"first_seen\" timestamp DEFAULT now(),\n\t\"score\" integer DEFAULT 0,\n\t\"identified_as_prospect_id\" uuid,\n\t\"created_at\" timestamp DEFAULT now()\n);",
  "CREATE TABLE IF NOT EXISTS \"whitelabel_settings\" (\n\t\"id\" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,\n\t\"tenant_id\" uuid NOT NULL,\n\t\"brand_name\" text,\n\t\"logo\" text,\n\t\"favicon\" text,\n\t\"primary_color\" text DEFAULT '#3b82f6',\n\t\"secondary_color\" text DEFAULT '#8b5cf6',\n\t\"custom_domain\" text,\n\t\"custom_css\" text,\n\t\"email_from_name\" text,\n\t\"email_from_address\" text,\n\t\"support_email\" text,\n\t\"privacy_url\" text,\n\t\"terms_url\" text,\n\t\"hide_argilette_branding\" boolean DEFAULT false,\n\t\"created_at\" timestamp DEFAULT now(),\n\t\"updated_at\" timestamp DEFAULT now(),\n\tCONSTRAINT \"whitelabel_settings_tenant_id_unique\" UNIQUE(\"tenant_id\")\n);",
  "CREATE INDEX IF NOT EXISTS \"idx_ab_tests_tenant\" ON \"ab_tests\" USING btree (\"tenant_id\");",
  "CREATE INDEX IF NOT EXISTS \"idx_accounts_tenant\" ON \"accounts\" USING btree (\"tenant_id\");",
  "CREATE INDEX IF NOT EXISTS \"idx_activities_tenant\" ON \"activities\" USING btree (\"tenant_id\");",
  "CREATE INDEX IF NOT EXISTS \"idx_activities_contact\" ON \"activities\" USING btree (\"contact_id\");",
  "CREATE INDEX IF NOT EXISTS \"idx_memories_tenant_agent\" ON \"agent_memories\" USING btree (\"tenant_id\",\"agent_type\");",
  "CREATE INDEX IF NOT EXISTS \"idx_memories_category\" ON \"agent_memories\" USING btree (\"tenant_id\",\"agent_type\",\"category\");",
  "CREATE INDEX IF NOT EXISTS \"idx_messages_session\" ON \"agent_messages\" USING btree (\"session_id\");",
  "CREATE INDEX IF NOT EXISTS \"idx_sessions_tenant_agent\" ON \"agent_sessions\" USING btree (\"tenant_id\",\"agent_type\");",
  "CREATE INDEX IF NOT EXISTS \"idx_sessions_user\" ON \"agent_sessions\" USING btree (\"user_id\");",
  "CREATE INDEX IF NOT EXISTS \"idx_agent_tasks_tenant\" ON \"agent_tasks\" USING btree (\"tenant_id\");",
  "CREATE INDEX IF NOT EXISTS \"idx_ai_usage_tenant\" ON \"ai_usage\" USING btree (\"tenant_id\");",
  "CREATE INDEX IF NOT EXISTS \"idx_campaigns_tenant\" ON \"campaigns\" USING btree (\"tenant_id\");",
  "CREATE INDEX IF NOT EXISTS \"idx_companies_tenant\" ON \"companies\" USING btree (\"tenant_id\");",
  "CREATE INDEX IF NOT EXISTS \"idx_companies_domain\" ON \"companies\" USING btree (\"domain\");",
  "CREATE INDEX IF NOT EXISTS \"idx_contacts_tenant\" ON \"contacts\" USING btree (\"tenant_id\");",
  "CREATE INDEX IF NOT EXISTS \"idx_contacts_email\" ON \"contacts\" USING btree (\"tenant_id\",\"email\");",
  "CREATE INDEX IF NOT EXISTS \"idx_deals_tenant\" ON \"deals\" USING btree (\"tenant_id\");",
  "CREATE INDEX IF NOT EXISTS \"idx_deals_stage\" ON \"deals\" USING btree (\"tenant_id\",\"stage\");",
  "CREATE INDEX IF NOT EXISTS \"idx_documents_tenant\" ON \"documents\" USING btree (\"tenant_id\");",
  "CREATE INDEX IF NOT EXISTS \"idx_employees_tenant\" ON \"employees\" USING btree (\"tenant_id\");",
  "CREATE INDEX IF NOT EXISTS \"idx_errors_severity\" ON \"error_logs\" USING btree (\"severity\");",
  "CREATE INDEX IF NOT EXISTS \"idx_errors_resolved\" ON \"error_logs\" USING btree (\"resolved\");",
  "CREATE INDEX IF NOT EXISTS \"idx_funnels_tenant\" ON \"funnels\" USING btree (\"tenant_id\");",
  "CREATE INDEX IF NOT EXISTS \"idx_health_type\" ON \"health_checks\" USING btree (\"check_type\");",
  "CREATE INDEX IF NOT EXISTS \"idx_intent_tenant\" ON \"intent_signals\" USING btree (\"tenant_id\");",
  "CREATE INDEX IF NOT EXISTS \"idx_invoices_tenant\" ON \"invoices\" USING btree (\"tenant_id\");",
  "CREATE INDEX IF NOT EXISTS \"idx_keywords_tenant\" ON \"keywords\" USING btree (\"tenant_id\");",
  "CREATE INDEX IF NOT EXISTS \"idx_landing_pages_tenant\" ON \"landing_pages\" USING btree (\"tenant_id\");",
  "CREATE INDEX IF NOT EXISTS \"idx_leads_tenant\" ON \"leads\" USING btree (\"tenant_id\");",
  "CREATE INDEX IF NOT EXISTS \"idx_orders_tenant\" ON \"orders\" USING btree (\"tenant_id\");",
  "CREATE INDEX IF NOT EXISTS \"idx_metrics_type_time\" ON \"performance_metrics\" USING btree (\"metric_type\",\"recorded_at\");",
  "CREATE INDEX IF NOT EXISTS \"idx_products_tenant\" ON \"products\" USING btree (\"tenant_id\");",
  "CREATE INDEX IF NOT EXISTS \"idx_project_tasks_project\" ON \"project_tasks\" USING btree (\"project_id\");",
  "CREATE INDEX IF NOT EXISTS \"idx_projects_tenant\" ON \"projects\" USING btree (\"tenant_id\");",
  "CREATE INDEX IF NOT EXISTS \"idx_prospects_tenant\" ON \"prospects\" USING btree (\"tenant_id\");",
  "CREATE INDEX IF NOT EXISTS \"idx_prospects_email\" ON \"prospects\" USING btree (\"tenant_id\",\"email\");",
  "CREATE INDEX IF NOT EXISTS \"idx_prospects_company\" ON \"prospects\" USING btree (\"company_id\");",
  "CREATE INDEX IF NOT EXISTS \"idx_reviews_tenant\" ON \"reputation_reviews\" USING btree (\"tenant_id\");",
  "CREATE INDEX IF NOT EXISTS \"idx_seo_projects_tenant\" ON \"seo_projects\" USING btree (\"tenant_id\");",
  "CREATE INDEX IF NOT EXISTS \"idx_sequences_tenant\" ON \"sequences\" USING btree (\"tenant_id\");",
  "CREATE INDEX IF NOT EXISTS \"idx_stores_tenant\" ON \"stores\" USING btree (\"tenant_id\");",
  "CREATE INDEX IF NOT EXISTS \"idx_tasks_tenant\" ON \"tasks\" USING btree (\"tenant_id\");",
  "CREATE INDEX IF NOT EXISTS \"idx_tasks_assignee\" ON \"tasks\" USING btree (\"assigned_to\");",
  "CREATE INDEX IF NOT EXISTS \"idx_technographics_company\" ON \"technographics\" USING btree (\"company_id\");",
  "CREATE INDEX IF NOT EXISTS \"idx_transactions_tenant\" ON \"transactions\" USING btree (\"tenant_id\");",
  "CREATE INDEX IF NOT EXISTS \"idx_users_tenant_email\" ON \"users\" USING btree (\"tenant_id\",\"email\");",
  "CREATE INDEX IF NOT EXISTS \"idx_visitors_tenant\" ON \"website_visitors\" USING btree (\"tenant_id\");"
];

async function migrate() {
  if (!process.env.DATABASE_URL) {
    console.log('[MIGRATE] No DATABASE_URL, skipping migration');
    return;
  }
  const client = new Client({ connectionString: process.env.DATABASE_URL, ssl: { rejectUnauthorized: false } });
  try {
    await client.connect();
    let created = 0, skipped = 0;
    for (const stmt of STATEMENTS) {
      try {
        await client.query(stmt);
        created++;
      } catch (err) {
        if (err.message.includes('already exists')) { skipped++; }
        else { console.warn('[MIGRATE] Skipped:', err.message.slice(0, 80)); }
      }
    }
    console.log('[MIGRATE] Done — created:', created, 'skipped:', skipped);
  } finally {
    await client.end().catch(() => {});
  }
}

migrate().catch(err => console.error('[MIGRATE] Error:', err.message));
