/**
 * ARGILETTE Language Context — full French (and multi-language) i18n system
 * Usage: const { t, lang, setLang } = useLanguage();
 */
import React, { createContext, useContext, useState, useEffect, useCallback } from "react";

// ── Translation dictionary ──────────────────────────────────────────────────
const translations: Record<string, Record<string, string>> = {
  en: {
    // ── Navigation ──
    nav_crm: "CRM",
    nav_intelligence: "Intelligence",
    nav_sales_marketing: "Sales & Marketing",
    nav_platform: "Platform",
    nav_operations: "Operations",
    nav_admin: "Admin",

    nav_dashboard: "Dashboard",
    nav_contacts: "Contacts",
    nav_leads: "Leads",
    nav_deals: "Deals",
    nav_tasks: "Tasks",
    nav_accounts: "Accounts",
    nav_analytics: "Analytics",
    nav_ai_tools: "AI Tools",
    nav_automation: "Automation",
    nav_lead_intelligence: "Lead Intelligence",
    nav_lead_gen: "AI Lead Gen",
    nav_marketplace: "Data Marketplace",
    nav_ai_agents: "AI Agents",
    nav_skills_library: "Skills Library",
    nav_marketing_hub: "Marketing Hub",
    nav_campaigns: "Campaigns",
    nav_invoices: "Invoices",
    nav_seo_platform: "SEO Platform",
    nav_ecommerce: "E-commerce",
    nav_finance: "Finance",
    nav_projects: "Projects",
    nav_employees: "Employees",
    nav_team: "Team",
    nav_settings: "Settings",
    nav_code_healing: "Code Healing",

    // ── Global UI ──
    save: "Save",
    save_changes: "Save Changes",
    cancel: "Cancel",
    delete: "Delete",
    edit: "Edit",
    add: "Add",
    add_new: "Add New",
    search: "Search",
    filter: "Filter",
    sort: "Sort",
    loading: "Loading...",
    error: "Error",
    success: "Success",
    warning: "Warning",
    info: "Information",
    welcome: "Welcome",
    logout: "Log Out",
    profile: "Profile",
    confirm: "Confirm",
    close: "Close",
    view: "View",
    export: "Export",
    import: "Import",
    refresh: "Refresh",
    back: "Back",
    next: "Next",
    previous: "Previous",
    submit: "Submit",
    send: "Send",
    update: "Update",
    create: "Create",
    remove: "Remove",
    manage: "Manage",
    generate: "Generate",
    copy: "Copy",
    copied: "Copied!",
    open: "Open",
    continue: "Continue",
    actions: "Actions",
    status: "Status",
    date: "Date",
    name: "Name",
    email: "Email",
    phone: "Phone",
    company: "Company",
    notes: "Notes",
    type: "Type",
    amount: "Amount",
    total: "Total",
    active: "Active",
    inactive: "Inactive",
    pending: "Pending",
    completed: "Completed",
    cancelled: "Cancelled",
    draft: "Draft",
    published: "Published",
    none: "None",
    all: "All",
    yes: "Yes",
    no: "No",
    or: "or",
    and: "and",
    description: "Description",
    title: "Title",
    category: "Category",
    tags: "Tags",
    price: "Price",
    quantity: "Quantity",
    inventory: "Inventory",
    currency: "Currency",
    language: "Language",
    theme: "Theme",
    notifications: "Notifications",
    privacy: "Privacy",
    security: "Security",
    billing: "Billing",
    upgrade: "Upgrade",
    plan: "Plan",
    usage: "Usage",
    limit: "Limit",
    unlimited: "Unlimited",
    today: "Today",
    this_week: "This week",
    this_month: "This month",
    no_data: "No data available",
    try_again: "Try again",

    // ── Dashboard ──
    dashboard_title: "Dashboard",
    dashboard_subtitle: "Your business at a glance",
    total_contacts: "Total Contacts",
    total_leads: "Total Leads",
    total_deals: "Total Deals",
    total_revenue: "Total Revenue",
    recent_activity: "Recent Activity",
    quick_actions: "Quick Actions",
    add_contact: "Add Contact",
    add_lead: "Add Lead",
    add_deal: "Add Deal",
    add_task: "Add Task",
    pipeline_overview: "Pipeline Overview",
    top_deals: "Top Deals",
    tasks_due: "Tasks Due",
    conversion_rate: "Conversion Rate",
    win_rate: "Win Rate",
    avg_deal_size: "Avg. Deal Size",
    active_deals: "Active Deals",

    // ── Contacts ──
    contacts_title: "Contacts",
    contacts_subtitle: "Manage your contacts",
    add_contact_btn: "Add Contact",
    contact_name: "Full Name",
    contact_email: "Email Address",
    contact_phone: "Phone Number",
    contact_company: "Company",
    contact_position: "Job Title",
    contact_source: "Source",
    contact_status: "Status",
    contact_tags: "Tags",
    contact_notes: "Notes",
    import_contacts: "Import Contacts",
    export_contacts: "Export Contacts",
    no_contacts: "No contacts yet",
    no_contacts_desc: "Add your first contact to get started",
    search_contacts: "Search contacts...",
    edit_contact: "Edit Contact",
    delete_contact: "Delete Contact",
    contact_details: "Contact Details",
    linkedin_url: "LinkedIn Profile",
    location: "Location",
    website: "Website",
    employees: "Employees",

    // ── Leads ──
    leads_title: "Leads",
    leads_subtitle: "Track and convert leads",
    add_lead_btn: "Add Lead",
    lead_name: "Lead Name",
    lead_email: "Email",
    lead_company: "Company",
    lead_source: "Source",
    lead_status: "Status",
    lead_score: "Score",
    lead_value: "Value",
    lead_notes: "Notes",
    no_leads: "No leads yet",
    no_leads_desc: "Add your first lead to start filling your pipeline",
    edit_lead: "Edit Lead",
    delete_lead: "Delete Lead",
    convert_lead: "Convert to Contact",
    qualify_lead: "Qualify Lead",
    status_new: "New",
    status_contacted: "Contacted",
    status_qualified: "Qualified",
    status_lost: "Lost",
    status_converted: "Converted",
    search_leads: "Search leads...",

    // ── Deals ──
    deals_title: "Deals",
    deals_subtitle: "Manage your sales pipeline",
    add_deal_btn: "Add Deal",
    deal_name: "Deal Name",
    deal_value: "Deal Value",
    deal_stage: "Stage",
    deal_close_date: "Close Date",
    deal_contact: "Contact",
    deal_probability: "Probability",
    no_deals: "No deals yet",
    no_deals_desc: "Add your first deal to track your pipeline",
    pipeline: "Pipeline",
    stage_lead: "Lead",
    stage_prospect: "Prospect",
    stage_proposal: "Proposal",
    stage_negotiation: "Negotiation",
    stage_closed_won: "Closed Won",
    stage_closed_lost: "Closed Lost",

    // ── Tasks ──
    tasks_title: "Tasks",
    tasks_subtitle: "Manage your to-dos",
    add_task_btn: "Add Task",
    task_title: "Task Title",
    task_description: "Description",
    task_due_date: "Due Date",
    task_priority: "Priority",
    task_status: "Status",
    task_assigned: "Assigned To",
    no_tasks: "No tasks yet",
    no_tasks_desc: "Add your first task to stay organized",
    priority_low: "Low",
    priority_medium: "Medium",
    priority_high: "High",
    priority_urgent: "Urgent",
    due_today: "Due today",
    overdue: "Overdue",
    mark_complete: "Mark Complete",
    reopen: "Reopen",

    // ── Accounts ──
    accounts_title: "Accounts",
    accounts_subtitle: "Manage your company accounts",
    add_account_btn: "Add Account",
    account_name: "Company Name",
    account_industry: "Industry",
    account_size: "Company Size",
    account_website: "Website",
    account_revenue: "Annual Revenue",
    no_accounts: "No accounts yet",
    no_accounts_desc: "Add your first account to get started",

    // ── Analytics ──
    analytics_title: "Analytics",
    analytics_subtitle: "Insights and performance metrics",
    overview: "Overview",
    performance: "Performance",
    revenue_chart: "Revenue Chart",
    leads_chart: "Leads Over Time",
    conversion_funnel: "Conversion Funnel",
    top_sources: "Top Lead Sources",
    monthly_revenue: "Monthly Revenue",
    growth: "Growth",
    visitors: "Visitors",
    page_views: "Page Views",
    bounce_rate: "Bounce Rate",
    avg_session: "Avg. Session Duration",
    reports: "Reports",

    // ── AI Tools ──
    ai_tools_title: "AI Tools",
    ai_tools_subtitle: "Powered by Argilette AI",
    generate_content: "Generate Content",
    ai_writing: "AI Writing Assistant",
    email_templates: "Email Templates",
    seo_content: "SEO Content",
    social_media: "Social Media Posts",
    ad_copy: "Ad Copy",
    product_descriptions: "Product Descriptions",
    ai_analyze: "Analyze with AI",
    ai_suggest: "Get AI Suggestions",
    generating: "Generating...",
    tokens_used: "Tokens used",
    tokens_remaining: "Tokens remaining",

    // ── E-commerce ──
    ecommerce_title: "E-commerce",
    ecommerce_subtitle: "Manage your online stores",
    products_tab: "Products",
    orders_tab: "Orders",
    stores_tab: "Stores",
    inventory_tab: "Inventory",
    add_product: "Add Product",
    edit_product: "Edit Product",
    product_name: "Product Name",
    product_desc: "Description",
    product_price: "Price",
    compare_price: "Compare-at Price",
    product_sku: "SKU",
    product_category: "Category",
    product_inventory: "Inventory",
    product_images: "Images",
    product_tags: "Tags",
    featured_product: "Featured Product",
    available_sale: "Available for sale",
    track_inventory: "Track inventory",
    import_supplier: "Import from Supplier",
    supplier_url: "Supplier Website URL",
    no_products: "No products yet",
    no_products_desc: "Add your first product to start selling",
    total_stores: "Total Stores",
    total_products: "Total Products",
    total_orders: "Total Orders",
    total_revenue_ec: "Revenue",
    low_stock_alerts: "Low Stock Alerts",
    build_store: "Build Store with AI",
    visit_store: "Visit Store",
    store_name: "Store Name",
    store_domain: "Domain",
    store_settings: "Store Settings",
    stripe_public_key: "Stripe Publishable Key",
    stripe_secret_key: "Stripe Secret Key",
    logo_url: "Logo URL",
    banner_url: "Hero Banner URL",
    order_number: "Order #",
    customer: "Customer",
    order_status: "Status",
    payment_status: "Payment Status",
    order_date: "Date",
    out_of_stock: "Out of Stock",
    low_stock: "Low Stock",
    add_store: "Add Store",
    ai_build_store: "Build with AI",
    slug: "URL Slug",
    currency_ec: "Currency",
    is_published: "Published",
    products_count: "Products",
    orders_count: "Orders",
    revenue_ec: "Revenue",

    // ── Finance ──
    finance_title: "Finance",
    finance_subtitle: "Financial management",
    income: "Income",
    expenses: "Expenses",
    profit: "Profit",
    net_revenue: "Net Revenue",
    transactions: "Transactions",
    invoices_tab: "Invoices",
    payments: "Payments",
    tax: "Tax",
    bank_accounts: "Bank Accounts",

    // ── Marketing ──
    marketing_title: "Marketing Hub",
    marketing_subtitle: "Campaigns and outreach",
    campaigns_title: "Campaigns",
    campaigns_subtitle: "Manage marketing campaigns",
    create_campaign: "Create Campaign",
    campaign_name: "Campaign Name",
    campaign_type: "Type",
    campaign_status: "Status",
    campaign_budget: "Budget",
    campaign_audience: "Audience",
    send_email: "Send Email",
    send_sms: "Send SMS",
    email_campaign: "Email Campaign",
    sms_campaign: "SMS Campaign",
    social_campaign: "Social Campaign",
    no_campaigns: "No campaigns yet",

    // ── SEO ──
    seo_title: "SEO Platform",
    seo_subtitle: "Search engine optimization",
    keywords: "Keywords",
    keyword_research: "Keyword Research",
    site_audit: "Site Audit",
    backlinks: "Backlinks",
    rank_tracking: "Rank Tracking",
    competitor_analysis: "Competitor Analysis",
    content_intelligence: "Content Intelligence",
    local_seo: "Local SEO",
    seo_score: "SEO Score",
    search_volume: "Search Volume",
    difficulty: "Difficulty",
    position: "Position",
    impressions: "Impressions",
    clicks: "Clicks",

    // ── Projects ──
    projects_title: "Projects",
    projects_subtitle: "Project management",
    add_project: "Add Project",
    project_name: "Project Name",
    project_status: "Status",
    project_deadline: "Deadline",
    project_team: "Team",
    project_budget: "Budget",
    no_projects: "No projects yet",
    milestones: "Milestones",
    gantt_chart: "Gantt Chart",
    kanban: "Kanban Board",

    // ── Employees ──
    employees_title: "Employees",
    employees_subtitle: "HR management",
    add_employee: "Add Employee",
    employee_name: "Name",
    employee_position: "Position",
    employee_department: "Department",
    employee_email: "Email",
    employee_phone: "Phone",
    employee_status: "Status",
    no_employees: "No employees yet",
    department: "Department",
    hire_date: "Hire Date",
    salary: "Salary",

    // ── Team ──
    team_title: "Team",
    team_subtitle: "Manage team members and roles",
    team_members: "team members",
    invite_member: "Invite Member",
    member_name: "Name",
    member_email: "Email",
    member_role: "Role",
    member_status: "Status",
    no_members: "No team members yet",
    role_admin: "Admin",
    role_manager: "Manager",
    role_agent: "Agent",
    role_viewer: "Viewer",
    send_invite: "Send Invite",
    resend_invite: "Resend Invite",
    revoke_access: "Revoke Access",

    // ── Settings ──
    settings_title: "Settings",
    settings_subtitle: "Manage your account and preferences",
    profile_tab: "Profile",
    account_tab: "Account",
    notifications_tab: "Notifications",
    billing_tab: "Billing",
    security_tab: "Security",
    integrations_tab: "Integrations",
    language_tab: "Language",
    white_label_tab: "White Label",
    first_name: "First Name",
    last_name: "Last Name",
    email_address: "Email Address",
    phone_number: "Phone Number",
    timezone: "Timezone",
    change_password: "Change Password",
    current_password: "Current Password",
    new_password: "New Password",
    confirm_password: "Confirm Password",
    two_factor: "Two-Factor Authentication",
    choose_language: "Choose Language",
    language_saved: "Language preference saved",

    // ── Invoices ──
    invoices_title: "Invoices",
    invoices_subtitle: "Manage your invoices",
    create_invoice: "Create Invoice",
    invoice_number: "Invoice #",
    invoice_client: "Client",
    invoice_amount: "Amount",
    invoice_due: "Due Date",
    invoice_status: "Status",
    invoice_paid: "Paid",
    invoice_unpaid: "Unpaid",
    invoice_overdue: "Overdue",
    invoice_draft: "Draft",
    no_invoices: "No invoices yet",
    send_invoice: "Send Invoice",
    mark_paid: "Mark as Paid",
    download_pdf: "Download PDF",

    // ── Workflows / Automation ──
    workflows_title: "Automation",
    workflows_subtitle: "Automate your business processes",
    create_workflow: "Create Workflow",
    workflow_name: "Workflow Name",
    workflow_trigger: "Trigger",
    workflow_actions: "Actions",
    workflow_status: "Status",
    no_workflows: "No workflows yet",
    trigger_new_lead: "New Lead",
    trigger_new_contact: "New Contact",
    trigger_deal_stage: "Deal Stage Change",
    trigger_form: "Form Submission",
    action_send_email: "Send Email",
    action_create_task: "Create Task",
    action_notify: "Send Notification",
    action_update: "Update Record",

    // ── AI Agents ──
    agents_title: "AI Agents",
    agents_subtitle: "Autonomous AI workers",
    agent_social: "Social Author",
    agent_sdr: "SDR Outreach",
    agent_reply: "Reply Handler",
    agent_closer: "Deal Closer",
    agent_chatbot: "Chat Bot",
    agent_scorer: "Lead Scorer",
    agent_status_active: "Active",
    agent_status_idle: "Idle",
    agent_status_paused: "Paused",
    agent_tasks_today: "Tasks today",
    agent_configure: "Configure",
    agent_activate: "Activate",
    agent_pause: "Pause",
    agent_logs: "View Logs",

    // ── Intelligence ──
    intelligence_title: "Lead Intelligence",
    intelligence_subtitle: "AI-powered lead research",
    research_lead: "Research Lead",
    enrich_data: "Enrich Data",
    find_decision_makers: "Find Decision Makers",
    company_insights: "Company Insights",
    news_mentions: "News Mentions",
    social_presence: "Social Presence",
    ai_score: "AI Score",
    confidence: "Confidence",

    // ── Skills ──
    skills_title: "Skills Library",
    skills_subtitle: "AI-powered tools and templates",
    run_skill: "Run Skill",
    skill_category: "Category",
    skill_inputs: "Inputs",
    skill_output: "Output",
    no_skills: "No skills found",
    search_skills: "Search skills...",

    // ── Lead Gen ──
    leadgen_title: "AI Lead Generation",
    leadgen_subtitle: "Autonomous prospecting powered by AI",
    tab_dashboard: "Dashboard",
    tab_prospects: "Prospects",
    tab_companies: "Companies",
    tab_intent: "Intent Signals",
    tab_email_verifier: "Email Verifier",
    tab_tech_scanner: "Tech Scanner",
    run_campaign: "Run Campaign",
    new_campaign: "New Campaign",
    total_prospects: "Total Prospects",
    companies_tracked: "Companies Tracked",
    emails_verified: "Emails Verified",
    ai_campaigns_run: "AI Campaigns Run",
    campaign_running: "Campaign Running",
    campaign_complete: "Campaign Complete",
    campaign_failed: "Campaign Failed",
    import_as_lead: "Import as Lead",
    verify_email: "Verify Email",
    scan_tech: "Scan Technology",
    email_placeholder: "Enter email to verify...",
    domain_placeholder: "Enter domain to scan...",
    no_prospects: "No prospects yet",
    no_companies: "No companies tracked",
    no_intent_signals: "No intent signals detected",
    enrichment_depth: "Enrichment Depth",
    target_industry: "Target Industry",
    target_location: "Target Location (optional)",
    target_count: "Target Count",
    campaign_keywords: "Keywords (comma-separated)",

    // ── Code Healing ──
    healing_title: "Code Healing",
    healing_subtitle: "Automated system diagnostics",
    last_scan: "Last Scan",
    issues_found: "Issues Found",
    issues_fixed: "Issues Fixed",
    run_scan: "Run Scan",
    scanning: "Scanning...",
    no_issues: "No issues found",
    system_health: "System Health",
    uptime: "Uptime",
    memory: "Memory",
    cpu: "CPU",
    database: "Database",

    // ── Storefront ──
    shop: "Shop",
    about: "About",
    contact: "Contact",
    add_to_cart: "Add to Cart",
    view_cart: "View Cart",
    checkout: "Checkout",
    your_cart: "Your Cart",
    cart_empty: "Your cart is empty",
    order_summary: "Order Summary",
    shipping: "Shipping",
    subtotal: "Subtotal",
    place_order: "Place Order",
    order_confirmed: "Order Confirmed",
    continue_shopping: "Continue Shopping",
    quick_view: "Quick View",
    featured: "Featured",
    in_stock: "In Stock",
    search_products: "Search products...",
    our_products: "Our Products",
    contact_shipping: "Contact & Shipping",
    full_name: "Full Name",
    email_address_sf: "Email",
    address: "Address",
    city: "City",
    state: "State",
    zip: "ZIP Code",
    country: "Country",
    phone_optional: "Phone (optional)",
    continue_payment: "Continue to Payment →",
    back_shipping: "← Back to shipping info",
    pay_now: "Pay",
    processing: "Processing...",
    manual_order: "Manual Order",
    trust_secure: "Secure Checkout",
    trust_shipping: "Fast Shipping",
    trust_quality: "Quality Guarantee",
    trust_support: "24/7 Support",
    items: "items",
    sort_default: "Sort: Default",
    sort_price_asc: "Price: Low → High",
    sort_price_desc: "Price: High → Low",
    sort_name: "Name A–Z",
    no_products_sf: "Products Coming Soon",
    no_products_sf_desc: "The store owner is adding products. Check back soon!",
    clear_search: "Clear Search",
    no_results: "No results found",
    try_different: "Try a different search term",
    message_sent: "Message Sent!",
    message_sent_desc: "We'll get back to you as soon as possible.",
    your_name: "Your Name",
    your_message: "Message",
    send_message: "Send Message →",
    powered_by: "Powered by",
    quick_links: "Quick Links",
    customer_service: "Customer Service",
    shipping_policy: "Shipping Policy",
    return_policy: "Return Policy",
    faq: "FAQ",
    all_rights: "All rights reserved",
    who_we_serve: "Who we serve",
    card_payment: "Card Payment",
    
    // ── Login / Register ──
    login_title: "Welcome back",
    login_subtitle: "Sign in to your account",
    email_label: "Email",
    password_label: "Password",
    sign_in: "Sign In",
    signing_in: "Signing in...",
    forgot_password: "Forgot password?",
    no_account: "Don't have an account?",
    start_trial: "Start free trial",
    register_title: "Create your account",
    register_subtitle: "Start your free trial today",
    sign_up: "Sign Up",
    already_account: "Already have an account?",
    sign_in_link: "Sign in",
    company_name_label: "Company Name",
    
    // ── Common status values ──
    status_active: "Active",
    status_inactive: "Inactive",
    status_pending: "Pending",
    status_completed: "Completed",
    status_cancelled: "Cancelled",
    status_draft: "Draft",
    status_paid: "Paid",
    status_overdue: "Overdue",
    status_processing: "Processing",
    status_shipped: "Shipped",
    status_delivered: "Delivered",
    status_open: "Open",
    status_won: "Won",

    // ── Landing Page ──
    landing_nav_features: "Features",
    landing_nav_agency: "Agency",
    landing_nav_pricing: "Pricing",
    landing_nav_contact: "Contact",
    landing_nav_signin: "Sign in",
    landing_nav_getstarted: "Get started free",
    landing_hero_badge_teams: "For Sales Teams",
    landing_hero_badge_agencies: "For Agencies — White Label Ready",
    landing_hero_h1_part1: "The CRM agencies resell.",
    landing_hero_h1_part2: "Teams love. Clients never see.",
    landing_hero_sub: "Full CRM + AI employees + white-label branding. Sell it under your own name at your own price — or use it for your team. 90% cheaper than building your own stack.",
    landing_hero_cta_trial: "Start free 14-day trial",
    landing_hero_cta_agency: "Agency pricing",
    landing_hero_no_card: "No credit card required · Cancel anytime · Setup in 2 minutes",
    landing_stat_agencies: "Agencies using it",
    landing_stat_cheaper: "Cheaper than alternatives",
    landing_stat_rating: "Average rating",
    landing_stat_whitelabel: "White-label ready",
    landing_replaces: "REPLACES ALL OF THESE",
    landing_for_label: "BUILT FOR TWO KINDS OF TEAMS",
    landing_for_h2: "One platform. Two powerful use cases.",
    landing_for_sub: "Whether you're running sales in-house or reselling CRM to your clients, ARGILETTE is built for you.",
    landing_for_teams: "Sales Teams",
    landing_for_agencies_tab: "Agencies & Resellers",
    landing_for_t1_title: "Manage your pipeline",
    landing_for_t1_desc: "Full CRM with contacts, leads, deals and visual pipeline boards.",
    landing_for_t2_title: "AI does the heavy lifting",
    landing_for_t2_desc: "6 AI agents handle outreach, qualification and follow-up around the clock.",
    landing_for_t3_title: "Run email campaigns",
    landing_for_t3_desc: "Send targeted campaigns with real-time open, click and reply analytics.",
    landing_for_t4_title: "Track every metric",
    landing_for_t4_desc: "Revenue dashboards, team performance reports and pipeline forecasts.",
    landing_for_a1_title: "Your brand everywhere",
    landing_for_a1_desc: "Logo, colours, favicon, domain — clients never see ARGILETTE.",
    landing_for_a2_title: "Isolated workspaces",
    landing_for_a2_desc: "Each client gets their own secure environment. Zero data bleed between accounts.",
    landing_for_a3_title: "Keep 100% margin",
    landing_for_a3_desc: "You set your own price. We charge you wholesale. You keep the difference.",
    landing_for_a4_title: "Custom domains",
    landing_for_a4_desc: "crm.yourclient.com with auto SSL. Point-and-click setup in minutes.",
    landing_feat_label: "FEATURES",
    landing_feat_h2: "Everything you need to close more deals",
    landing_feat_sub: "Replace 6 separate tools with one unified platform and save thousands per month.",
    landing_feat_f1_title: "Contact & Lead Management",
    landing_feat_f1_desc: "Centralize every contact and lead. Track all interactions, score prospects, and turn conversations into revenue.",
    landing_feat_f2_title: "Visual Sales Pipeline",
    landing_feat_f2_desc: "Drag-and-drop Kanban boards with 6 customizable stages. See your entire revenue pipeline at a glance.",
    landing_feat_f3_title: "6 AI Employees",
    landing_feat_f3_desc: "Autonomous agents for outreach, lead scoring, reply handling, closing, chat qualification, and social posting.",
    landing_feat_f4_title: "Email Campaigns",
    landing_feat_f4_desc: "Design, schedule and send targeted email and SMS campaigns from one unified dashboard with real-time analytics.",
    landing_feat_f5_title: "Analytics & Reporting",
    landing_feat_f5_desc: "Real-time dashboards showing revenue trends, team performance, campaign ROI and full pipeline health.",
    landing_feat_f6_title: "Enterprise Security",
    landing_feat_f6_desc: "Multi-tenant isolation, role-based access control, audit logs and SOC 2-aligned data protection.",
    landing_ai_label: "AI EMPLOYEES",
    landing_ai_h2_a: "6 AI agents working",
    landing_ai_h2_b: "while you sleep",
    landing_ai_sub: "Autonomous AI handles your entire sales workflow — from prospecting to closing. Each agent is purpose-built and learns from your data.",
    landing_ai_a1_name: "Prospector",
    landing_ai_a1_desc: "Finds and qualifies new leads from the web",
    landing_ai_a2_name: "Outreach Agent",
    landing_ai_a2_desc: "Writes and sends personalised cold emails",
    landing_ai_a3_name: "Reply Handler",
    landing_ai_a3_desc: "Responds to incoming leads within minutes",
    landing_ai_a4_name: "Closer",
    landing_ai_a4_desc: "Crafts proposals and follow-up sequences",
    landing_ai_a5_name: "Chat Qualifier",
    landing_ai_a5_desc: "Qualifies website visitors in real-time",
    landing_ai_a6_name: "Social Poster",
    landing_ai_a6_desc: "Publishes content across your social channels",
    landing_wl_label: "WHITE LABEL & AGENCY",
    landing_wl_h2_a: "Sell it as your own.",
    landing_wl_h2_b: "Keep 100% of the revenue.",
    landing_wl_sub: "Agencies and resellers white-label ARGILETTE under their own brand. Logo, colours, domain, emails — your clients never see our name.",
    landing_wl_f1_title: "Full brand replacement",
    landing_wl_f1_desc: "Your logo, colours, favicon. Every pixel reflects your brand — ARGILETTE is invisible to your clients.",
    landing_wl_f2_title: "Custom domain per client",
    landing_wl_f2_desc: "Point crm.yourclient.com to their workspace. SSL provisioned automatically.",
    landing_wl_f3_title: "Branded transactional emails",
    landing_wl_f3_desc: "Welcome, invite and receipt emails sent from your company name and domain.",
    landing_wl_f4_title: "Isolated client workspaces",
    landing_wl_f4_desc: "Each client sits in their own secure, isolated environment. Zero data bleed.",
    landing_wl_f5_title: "Your pricing, your margin",
    landing_wl_f5_desc: "We charge you wholesale. You set your own price and keep the entire difference.",
    landing_wl_f6_title: "API & webhook access",
    landing_wl_f6_desc: "Connect to your existing billing portals, reporting dashboards, or PSA tools.",
    landing_wl_without: "WITHOUT WHITE LABEL",
    landing_wl_with: "WITH WHITE LABEL",
    landing_wl_what_clients_see: "What your clients see",
    landing_wl_bad1: "ARGILETTE logo in sidebar",
    landing_wl_bad2: "info@argilette.com in emails",
    landing_wl_bad3: "'Powered by ARGILETTE' mentions",
    landing_wl_bad4: "argilette.org in browser",
    landing_wl_good1: "Your logo on every page",
    landing_wl_good2: "Your email address throughout",
    landing_wl_good3: "Your company name everywhere",
    landing_wl_good4: "crm.yourdomain.com with SSL",
    landing_wl_existing: "Already a Business or Enterprise customer?",
    landing_wl_existing_desc: "White-label is already included. Go to Settings → White Label to activate it right now.",
    landing_test_label: "TESTIMONIALS",
    landing_test_h2: "Loved by teams and agencies",
    landing_test_t1_text: "We moved from HubSpot and cut our CRM costs by 70%. The AI email generation alone saves 3 hours a week per rep.",
    landing_test_t1_name: "Sarah Mitchell",
    landing_test_t1_role: "CTO, TechVision Inc",
    landing_test_t2_text: "The multi-tenant setup was perfect for our agency. Each client gets their own isolated workspace — fully white-labelled under our brand.",
    landing_test_t2_name: "Marcus Johnson",
    landing_test_t2_role: "VP Operations, HealthBridge",
    landing_test_t3_text: "We resell this to 14 clients at our own pricing. The white-label is seamless — none of them know it's ARGILETTE under the hood.",
    landing_test_t3_name: "Aisha Okonkwo",
    landing_test_t3_role: "CEO, GreenScale Digital",
    landing_price_label: "PRICING",
    landing_price_h2: "Transparent pricing for every use case",
    landing_price_sub: "Whether you're a team or an agency, we have a plan for you.",
    landing_price_for_teams: "For Teams",
    landing_price_for_agencies: "For Agencies",
    landing_price_popular: "MOST POPULAR",
    landing_price_footer: "All plans include a 14-day free trial · No credit card required · Cancel anytime",
    landing_price_cta_trial: "Start free trial",
    landing_price_cta_contact: "Contact sales",
    landing_price_cta_start: "Get started",
    landing_cta_h2: "Ready to launch your own CRM?",
    landing_cta_sub: "Join 3,400+ agencies and sales teams. Start your trial today — or talk to us about white-label and agency pricing.",
    landing_cta_trial: "Start free trial",
    landing_cta_agency: "Talk to agency sales",
    landing_cta_footer: "14 days free · No credit card · Cancel anytime",
    landing_footer_rights: "© 2026 ARGILETTE LLC. All rights reserved.",
    landing_footer_privacy: "Privacy",
    landing_footer_terms: "Terms",
    landing_footer_security: "Security",
  },

  // ────────────────────────────────────────────────────────────────
  // FRENCH TRANSLATIONS
  // ────────────────────────────────────────────────────────────────
  fr: {
    // ── Navigation ──
    nav_crm: "CRM",
    nav_intelligence: "Intelligence",
    nav_sales_marketing: "Ventes & Marketing",
    nav_platform: "Plateforme",
    nav_operations: "Opérations",
    nav_admin: "Administration",

    nav_dashboard: "Tableau de bord",
    nav_contacts: "Contacts",
    nav_leads: "Prospects",
    nav_deals: "Affaires",
    nav_tasks: "Tâches",
    nav_accounts: "Comptes",
    nav_analytics: "Analytique",
    nav_ai_tools: "Outils IA",
    nav_automation: "Automatisation",
    nav_lead_intelligence: "Intelligence Prospects",
    nav_lead_gen: "Génération IA",
    nav_marketplace: "Marché de Données",
    nav_ai_agents: "Agents IA",
    nav_skills_library: "Bibliothèque de Compétences",
    nav_marketing_hub: "Hub Marketing",
    nav_campaigns: "Campagnes",
    nav_invoices: "Factures",
    nav_seo_platform: "Plateforme SEO",
    nav_ecommerce: "E-commerce",
    nav_finance: "Finance",
    nav_projects: "Projets",
    nav_employees: "Employés",
    nav_team: "Équipe",
    nav_settings: "Paramètres",
    nav_code_healing: "Autoréparation",

    // ── Global UI ──
    save: "Enregistrer",
    save_changes: "Enregistrer les modifications",
    cancel: "Annuler",
    delete: "Supprimer",
    edit: "Modifier",
    add: "Ajouter",
    add_new: "Ajouter",
    search: "Rechercher",
    filter: "Filtrer",
    sort: "Trier",
    loading: "Chargement...",
    error: "Erreur",
    success: "Succès",
    warning: "Avertissement",
    info: "Information",
    welcome: "Bienvenue",
    logout: "Déconnexion",
    profile: "Profil",
    confirm: "Confirmer",
    close: "Fermer",
    view: "Voir",
    export: "Exporter",
    import: "Importer",
    refresh: "Actualiser",
    back: "Retour",
    next: "Suivant",
    previous: "Précédent",
    submit: "Soumettre",
    send: "Envoyer",
    update: "Mettre à jour",
    create: "Créer",
    remove: "Retirer",
    manage: "Gérer",
    generate: "Générer",
    copy: "Copier",
    copied: "Copié !",
    open: "Ouvrir",
    continue: "Continuer",
    actions: "Actions",
    status: "Statut",
    date: "Date",
    name: "Nom",
    email: "E-mail",
    phone: "Téléphone",
    company: "Entreprise",
    notes: "Notes",
    type: "Type",
    amount: "Montant",
    total: "Total",
    active: "Actif",
    inactive: "Inactif",
    pending: "En attente",
    completed: "Terminé",
    cancelled: "Annulé",
    draft: "Brouillon",
    published: "Publié",
    none: "Aucun",
    all: "Tout",
    yes: "Oui",
    no: "Non",
    or: "ou",
    and: "et",
    description: "Description",
    title: "Titre",
    category: "Catégorie",
    tags: "Étiquettes",
    price: "Prix",
    quantity: "Quantité",
    inventory: "Inventaire",
    currency: "Devise",
    language: "Langue",
    theme: "Thème",
    notifications: "Notifications",
    privacy: "Confidentialité",
    security: "Sécurité",
    billing: "Facturation",
    upgrade: "Mise à niveau",
    plan: "Plan",
    usage: "Utilisation",
    limit: "Limite",
    unlimited: "Illimité",
    today: "Aujourd'hui",
    this_week: "Cette semaine",
    this_month: "Ce mois",
    no_data: "Aucune donnée disponible",
    try_again: "Réessayer",

    // ── Dashboard ──
    dashboard_title: "Tableau de bord",
    dashboard_subtitle: "Vue d'ensemble de votre activité",
    total_contacts: "Total Contacts",
    total_leads: "Total Prospects",
    total_deals: "Total Affaires",
    total_revenue: "Chiffre d'affaires",
    recent_activity: "Activité récente",
    quick_actions: "Actions rapides",
    add_contact: "Ajouter un contact",
    add_lead: "Ajouter un prospect",
    add_deal: "Ajouter une affaire",
    add_task: "Ajouter une tâche",
    pipeline_overview: "Aperçu du pipeline",
    top_deals: "Meilleures affaires",
    tasks_due: "Tâches à faire",
    conversion_rate: "Taux de conversion",
    win_rate: "Taux de réussite",
    avg_deal_size: "Valeur moyenne affaire",
    active_deals: "Affaires actives",

    // ── Contacts ──
    contacts_title: "Contacts",
    contacts_subtitle: "Gérer vos contacts",
    add_contact_btn: "Ajouter un contact",
    contact_name: "Nom complet",
    contact_email: "Adresse e-mail",
    contact_phone: "Numéro de téléphone",
    contact_company: "Entreprise",
    contact_position: "Poste",
    contact_source: "Source",
    contact_status: "Statut",
    contact_tags: "Étiquettes",
    contact_notes: "Notes",
    import_contacts: "Importer des contacts",
    export_contacts: "Exporter des contacts",
    no_contacts: "Aucun contact",
    no_contacts_desc: "Ajoutez votre premier contact pour commencer",
    search_contacts: "Rechercher des contacts...",
    edit_contact: "Modifier le contact",
    delete_contact: "Supprimer le contact",
    contact_details: "Détails du contact",
    linkedin_url: "Profil LinkedIn",
    location: "Localisation",
    website: "Site web",
    employees: "Employés",

    // ── Leads ──
    leads_title: "Prospects",
    leads_subtitle: "Suivre et convertir les prospects",
    add_lead_btn: "Ajouter un prospect",
    lead_name: "Nom du prospect",
    lead_email: "E-mail",
    lead_company: "Entreprise",
    lead_source: "Source",
    lead_status: "Statut",
    lead_score: "Score",
    lead_value: "Valeur",
    lead_notes: "Notes",
    no_leads: "Aucun prospect",
    no_leads_desc: "Ajoutez votre premier prospect pour remplir votre pipeline",
    edit_lead: "Modifier le prospect",
    delete_lead: "Supprimer le prospect",
    convert_lead: "Convertir en contact",
    qualify_lead: "Qualifier le prospect",
    status_new: "Nouveau",
    status_contacted: "Contacté",
    status_qualified: "Qualifié",
    status_lost: "Perdu",
    status_converted: "Converti",
    search_leads: "Rechercher des prospects...",

    // ── Deals ──
    deals_title: "Affaires",
    deals_subtitle: "Gérer votre pipeline commercial",
    add_deal_btn: "Ajouter une affaire",
    deal_name: "Nom de l'affaire",
    deal_value: "Valeur",
    deal_stage: "Étape",
    deal_close_date: "Date de clôture",
    deal_contact: "Contact",
    deal_probability: "Probabilité",
    no_deals: "Aucune affaire",
    no_deals_desc: "Ajoutez votre première affaire pour suivre votre pipeline",
    pipeline: "Pipeline",
    stage_lead: "Prospect",
    stage_prospect: "Intérêt",
    stage_proposal: "Proposition",
    stage_negotiation: "Négociation",
    stage_closed_won: "Gagné",
    stage_closed_lost: "Perdu",

    // ── Tasks ──
    tasks_title: "Tâches",
    tasks_subtitle: "Gérer vos tâches",
    add_task_btn: "Ajouter une tâche",
    task_title: "Titre de la tâche",
    task_description: "Description",
    task_due_date: "Date d'échéance",
    task_priority: "Priorité",
    task_status: "Statut",
    task_assigned: "Assigné à",
    no_tasks: "Aucune tâche",
    no_tasks_desc: "Ajoutez votre première tâche pour rester organisé",
    priority_low: "Faible",
    priority_medium: "Moyenne",
    priority_high: "Élevée",
    priority_urgent: "Urgent",
    due_today: "À rendre aujourd'hui",
    overdue: "En retard",
    mark_complete: "Marquer comme terminé",
    reopen: "Rouvrir",

    // ── Accounts ──
    accounts_title: "Comptes",
    accounts_subtitle: "Gérer vos comptes entreprises",
    add_account_btn: "Ajouter un compte",
    account_name: "Nom de l'entreprise",
    account_industry: "Secteur",
    account_size: "Taille",
    account_website: "Site web",
    account_revenue: "Chiffre d'affaires annuel",
    no_accounts: "Aucun compte",
    no_accounts_desc: "Ajoutez votre premier compte pour commencer",

    // ── Analytics ──
    analytics_title: "Analytique",
    analytics_subtitle: "Informations et indicateurs de performance",
    overview: "Vue d'ensemble",
    performance: "Performance",
    revenue_chart: "Graphique des revenus",
    leads_chart: "Prospects dans le temps",
    conversion_funnel: "Entonnoir de conversion",
    top_sources: "Meilleures sources de prospects",
    monthly_revenue: "Revenus mensuels",
    growth: "Croissance",
    visitors: "Visiteurs",
    page_views: "Pages vues",
    bounce_rate: "Taux de rebond",
    avg_session: "Durée moyenne de session",
    reports: "Rapports",

    // ── AI Tools ──
    ai_tools_title: "Outils IA",
    ai_tools_subtitle: "Propulsé par Argilette IA",
    generate_content: "Générer du contenu",
    ai_writing: "Assistant rédaction IA",
    email_templates: "Modèles d'e-mail",
    seo_content: "Contenu SEO",
    social_media: "Publications réseaux sociaux",
    ad_copy: "Texte publicitaire",
    product_descriptions: "Descriptions produits",
    ai_analyze: "Analyser avec l'IA",
    ai_suggest: "Suggestions IA",
    generating: "Génération en cours...",
    tokens_used: "Jetons utilisés",
    tokens_remaining: "Jetons restants",

    // ── E-commerce ──
    ecommerce_title: "E-commerce",
    ecommerce_subtitle: "Gérez vos boutiques en ligne",
    products_tab: "Produits",
    orders_tab: "Commandes",
    stores_tab: "Boutiques",
    inventory_tab: "Inventaire",
    add_product: "Ajouter un produit",
    edit_product: "Modifier le produit",
    product_name: "Nom du produit",
    product_desc: "Description",
    product_price: "Prix",
    compare_price: "Prix barré",
    product_sku: "Référence",
    product_category: "Catégorie",
    product_inventory: "Inventaire",
    product_images: "Images",
    product_tags: "Étiquettes",
    featured_product: "Produit vedette",
    available_sale: "Disponible à la vente",
    track_inventory: "Suivre l'inventaire",
    import_supplier: "Importer du fournisseur",
    supplier_url: "URL du site fournisseur",
    no_products: "Aucun produit",
    no_products_desc: "Ajoutez votre premier produit pour commencer à vendre",
    total_stores: "Boutiques",
    total_products: "Produits",
    total_orders: "Commandes",
    total_revenue_ec: "Revenus",
    low_stock_alerts: "Alertes stock faible",
    build_store: "Créer une boutique avec l'IA",
    visit_store: "Visiter la boutique",
    store_name: "Nom de la boutique",
    store_domain: "Domaine",
    store_settings: "Paramètres de la boutique",
    stripe_public_key: "Clé publique Stripe",
    stripe_secret_key: "Clé secrète Stripe",
    logo_url: "URL du logo",
    banner_url: "URL de la bannière",
    order_number: "Commande n°",
    customer: "Client",
    order_status: "Statut",
    payment_status: "Paiement",
    order_date: "Date",
    out_of_stock: "Rupture de stock",
    low_stock: "Stock faible",
    add_store: "Ajouter une boutique",
    ai_build_store: "Créer avec l'IA",
    slug: "Identifiant URL",
    currency_ec: "Devise",
    is_published: "Publié",
    products_count: "Produits",
    orders_count: "Commandes",
    revenue_ec: "Revenus",

    // ── Finance ──
    finance_title: "Finance",
    finance_subtitle: "Gestion financière",
    income: "Revenus",
    expenses: "Dépenses",
    profit: "Profit",
    net_revenue: "Revenu net",
    transactions: "Transactions",
    invoices_tab: "Factures",
    payments: "Paiements",
    tax: "Taxe",
    bank_accounts: "Comptes bancaires",

    // ── Marketing ──
    marketing_title: "Hub Marketing",
    marketing_subtitle: "Campagnes et communication",
    campaigns_title: "Campagnes",
    campaigns_subtitle: "Gérer les campagnes marketing",
    create_campaign: "Créer une campagne",
    campaign_name: "Nom de la campagne",
    campaign_type: "Type",
    campaign_status: "Statut",
    campaign_budget: "Budget",
    campaign_audience: "Audience",
    send_email: "Envoyer un e-mail",
    send_sms: "Envoyer un SMS",
    email_campaign: "Campagne e-mail",
    sms_campaign: "Campagne SMS",
    social_campaign: "Campagne sociale",
    no_campaigns: "Aucune campagne",

    // ── SEO ──
    seo_title: "Plateforme SEO",
    seo_subtitle: "Optimisation pour les moteurs de recherche",
    keywords: "Mots-clés",
    keyword_research: "Recherche de mots-clés",
    site_audit: "Audit du site",
    backlinks: "Liens entrants",
    rank_tracking: "Suivi des positions",
    competitor_analysis: "Analyse concurrentielle",
    content_intelligence: "Intelligence de contenu",
    local_seo: "SEO local",
    seo_score: "Score SEO",
    search_volume: "Volume de recherche",
    difficulty: "Difficulté",
    position: "Position",
    impressions: "Impressions",
    clicks: "Clics",

    // ── Projects ──
    projects_title: "Projets",
    projects_subtitle: "Gestion de projets",
    add_project: "Ajouter un projet",
    project_name: "Nom du projet",
    project_status: "Statut",
    project_deadline: "Échéance",
    project_team: "Équipe",
    project_budget: "Budget",
    no_projects: "Aucun projet",
    milestones: "Jalons",
    gantt_chart: "Diagramme de Gantt",
    kanban: "Tableau Kanban",

    // ── Employees ──
    employees_title: "Employés",
    employees_subtitle: "Gestion des ressources humaines",
    add_employee: "Ajouter un employé",
    employee_name: "Nom",
    employee_position: "Poste",
    employee_department: "Département",
    employee_email: "E-mail",
    employee_phone: "Téléphone",
    employee_status: "Statut",
    no_employees: "Aucun employé",
    department: "Département",
    hire_date: "Date d'embauche",
    salary: "Salaire",

    // ── Team ──
    team_title: "Équipe",
    team_subtitle: "Gérer les membres et les rôles",
    team_members: "membres",
    invite_member: "Inviter un membre",
    member_name: "Nom",
    member_email: "E-mail",
    member_role: "Rôle",
    member_status: "Statut",
    no_members: "Aucun membre",
    role_admin: "Administrateur",
    role_manager: "Responsable",
    role_agent: "Agent",
    role_viewer: "Observateur",
    send_invite: "Envoyer l'invitation",
    resend_invite: "Renvoyer l'invitation",
    revoke_access: "Révoquer l'accès",

    // ── Settings ──
    settings_title: "Paramètres",
    settings_subtitle: "Gérer votre compte et vos préférences",
    profile_tab: "Profil",
    account_tab: "Compte",
    notifications_tab: "Notifications",
    billing_tab: "Facturation",
    security_tab: "Sécurité",
    integrations_tab: "Intégrations",
    language_tab: "Langue",
    white_label_tab: "Marque blanche",
    first_name: "Prénom",
    last_name: "Nom de famille",
    email_address: "Adresse e-mail",
    phone_number: "Numéro de téléphone",
    timezone: "Fuseau horaire",
    change_password: "Changer le mot de passe",
    current_password: "Mot de passe actuel",
    new_password: "Nouveau mot de passe",
    confirm_password: "Confirmer le mot de passe",
    two_factor: "Authentification à deux facteurs",
    choose_language: "Choisir la langue",
    language_saved: "Préférence de langue enregistrée",

    // ── Invoices ──
    invoices_title: "Factures",
    invoices_subtitle: "Gérer vos factures",
    create_invoice: "Créer une facture",
    invoice_number: "Facture n°",
    invoice_client: "Client",
    invoice_amount: "Montant",
    invoice_due: "Date d'échéance",
    invoice_status: "Statut",
    invoice_paid: "Payée",
    invoice_unpaid: "Impayée",
    invoice_overdue: "En retard",
    invoice_draft: "Brouillon",
    no_invoices: "Aucune facture",
    send_invoice: "Envoyer la facture",
    mark_paid: "Marquer comme payée",
    download_pdf: "Télécharger le PDF",

    // ── Workflows ──
    workflows_title: "Automatisation",
    workflows_subtitle: "Automatisez vos processus métier",
    create_workflow: "Créer un workflow",
    workflow_name: "Nom du workflow",
    workflow_trigger: "Déclencheur",
    workflow_actions: "Actions",
    workflow_status: "Statut",
    no_workflows: "Aucun workflow",
    trigger_new_lead: "Nouveau prospect",
    trigger_new_contact: "Nouveau contact",
    trigger_deal_stage: "Changement d'étape",
    trigger_form: "Soumission de formulaire",
    action_send_email: "Envoyer un e-mail",
    action_create_task: "Créer une tâche",
    action_notify: "Envoyer une notification",
    action_update: "Mettre à jour l'enregistrement",

    // ── AI Agents ──
    agents_title: "Agents IA",
    agents_subtitle: "Travailleurs IA autonomes",
    agent_social: "Auteur Social",
    agent_sdr: "Prospection SDR",
    agent_reply: "Gestionnaire de réponses",
    agent_closer: "Closeur d'affaires",
    agent_chatbot: "Bot de chat",
    agent_scorer: "Scoreur de prospects",
    agent_status_active: "Actif",
    agent_status_idle: "Inactif",
    agent_status_paused: "En pause",
    agent_tasks_today: "Tâches aujourd'hui",
    agent_configure: "Configurer",
    agent_activate: "Activer",
    agent_pause: "Mettre en pause",
    agent_logs: "Voir les journaux",

    // ── Intelligence ──
    intelligence_title: "Intelligence Prospects",
    intelligence_subtitle: "Recherche de prospects assistée par IA",
    research_lead: "Rechercher le prospect",
    enrich_data: "Enrichir les données",
    find_decision_makers: "Trouver les décideurs",
    company_insights: "Informations sur l'entreprise",
    news_mentions: "Mentions dans les actualités",
    social_presence: "Présence sociale",
    ai_score: "Score IA",
    confidence: "Confiance",

    // ── Lead Gen ──
    leadgen_title: "Génération de Leads IA",
    leadgen_subtitle: "Prospection autonome propulsée par l'IA",
    tab_dashboard: "Tableau de bord",
    tab_prospects: "Prospects",
    tab_companies: "Entreprises",
    tab_intent: "Signaux d'Intention",
    tab_email_verifier: "Vérificateur d'Email",
    tab_tech_scanner: "Scanner Technologique",
    run_campaign: "Lancer la Campagne",
    new_campaign: "Nouvelle Campagne",
    total_prospects: "Total Prospects",
    companies_tracked: "Entreprises Suivies",
    emails_verified: "Emails Vérifiés",
    ai_campaigns_run: "Campagnes IA Lancées",
    campaign_running: "Campagne en Cours",
    campaign_complete: "Campagne Terminée",
    campaign_failed: "Campagne Échouée",
    import_as_lead: "Importer en Prospect",
    verify_email: "Vérifier l'Email",
    scan_tech: "Scanner la Technologie",
    email_placeholder: "Entrer un email à vérifier...",
    domain_placeholder: "Entrer un domaine à scanner...",
    no_prospects: "Aucun prospect pour l'instant",
    no_companies: "Aucune entreprise suivie",
    no_intent_signals: "Aucun signal d'intention détecté",
    enrichment_depth: "Niveau d'Enrichissement",
    target_industry: "Secteur Cible",
    target_location: "Localisation Cible (optionnel)",
    target_count: "Nombre Cible",
    campaign_keywords: "Mots-clés (séparés par virgule)",

    // ── Skills ──
    skills_title: "Bibliothèque de Compétences",
    skills_subtitle: "Outils et modèles assistés par IA",
    run_skill: "Exécuter",
    skill_category: "Catégorie",
    skill_inputs: "Entrées",
    skill_output: "Résultat",
    no_skills: "Aucune compétence trouvée",
    search_skills: "Rechercher des compétences...",

    // ── Code Healing ──
    healing_title: "Autoréparation du code",
    healing_subtitle: "Diagnostics système automatisés",
    last_scan: "Dernier scan",
    issues_found: "Problèmes détectés",
    issues_fixed: "Problèmes corrigés",
    run_scan: "Lancer le scan",
    scanning: "Scan en cours...",
    no_issues: "Aucun problème détecté",
    system_health: "Santé du système",
    uptime: "Disponibilité",
    memory: "Mémoire",
    cpu: "CPU",
    database: "Base de données",

    // ── Storefront ──
    shop: "Boutique",
    about: "À propos",
    contact: "Contact",
    add_to_cart: "Ajouter au panier",
    view_cart: "Voir le panier",
    checkout: "Passer la commande",
    your_cart: "Votre panier",
    cart_empty: "Votre panier est vide",
    order_summary: "Résumé de la commande",
    shipping: "Livraison",
    subtotal: "Sous-total",
    place_order: "Passer la commande",
    order_confirmed: "Commande confirmée !",
    continue_shopping: "Continuer mes achats",
    quick_view: "Aperçu rapide",
    featured: "Vedette",
    in_stock: "En stock",
    search_products: "Rechercher des produits...",
    our_products: "Nos Produits",
    contact_shipping: "Contact & Livraison",
    full_name: "Nom complet",
    email_address_sf: "E-mail",
    address: "Adresse",
    city: "Ville",
    state: "Région",
    zip: "Code postal",
    country: "Pays",
    phone_optional: "Téléphone (facultatif)",
    continue_payment: "Continuer vers le paiement →",
    back_shipping: "← Retour aux informations de livraison",
    pay_now: "Payer",
    processing: "Traitement en cours...",
    manual_order: "Commande manuelle",
    trust_secure: "Paiement sécurisé",
    trust_shipping: "Livraison rapide",
    trust_quality: "Garantie qualité",
    trust_support: "Support 24h/24",
    items: "articles",
    sort_default: "Tri : Par défaut",
    sort_price_asc: "Prix : Croissant",
    sort_price_desc: "Prix : Décroissant",
    sort_name: "Nom A–Z",
    no_products_sf: "Produits bientôt disponibles",
    no_products_sf_desc: "Le propriétaire de la boutique ajoute des produits. Revenez bientôt !",
    clear_search: "Effacer la recherche",
    no_results: "Aucun résultat",
    try_different: "Essayez un terme de recherche différent",
    message_sent: "Message envoyé !",
    message_sent_desc: "Nous vous répondrons dès que possible.",
    your_name: "Votre nom",
    your_message: "Message",
    send_message: "Envoyer le message →",
    powered_by: "Propulsé par",
    quick_links: "Liens rapides",
    customer_service: "Service client",
    shipping_policy: "Politique de livraison",
    return_policy: "Politique de retour",
    faq: "FAQ",
    all_rights: "Tous droits réservés",
    who_we_serve: "Qui nous servons",
    card_payment: "Paiement par carte",

    // ── Login / Register ──
    login_title: "Bon retour",
    login_subtitle: "Connectez-vous à votre compte",
    email_label: "E-mail",
    password_label: "Mot de passe",
    sign_in: "Se connecter",
    signing_in: "Connexion en cours...",
    forgot_password: "Mot de passe oublié ?",
    no_account: "Vous n'avez pas de compte ?",
    start_trial: "Commencer l'essai gratuit",
    register_title: "Créer votre compte",
    register_subtitle: "Commencez votre essai gratuit aujourd'hui",
    sign_up: "S'inscrire",
    already_account: "Vous avez déjà un compte ?",
    sign_in_link: "Se connecter",
    company_name_label: "Nom de l'entreprise",

    // ── Common status values ──
    status_active: "Actif",
    status_inactive: "Inactif",
    status_pending: "En attente",
    status_completed: "Terminé",
    status_cancelled: "Annulé",
    status_draft: "Brouillon",
    status_paid: "Payé",
    status_overdue: "En retard",
    status_processing: "En traitement",
    status_shipped: "Expédié",
    status_delivered: "Livré",
    status_open: "Ouvert",
    status_won: "Gagné",

    // ── Landing Page ──
    landing_nav_features: "Fonctionnalités",
    landing_nav_agency: "Agence",
    landing_nav_pricing: "Tarifs",
    landing_nav_contact: "Contact",
    landing_nav_signin: "Se connecter",
    landing_nav_getstarted: "Commencer gratuitement",
    landing_hero_badge_teams: "Pour les équipes commerciales",
    landing_hero_badge_agencies: "Pour les agences — Marque blanche incluse",
    landing_hero_h1_part1: "Le CRM que les agences revendent.",
    landing_hero_h1_part2: "Que les équipes adorent. Invisible pour les clients.",
    landing_hero_sub: "CRM complet + employés IA + marque blanche. Vendez-le sous votre propre nom à votre propre prix — ou utilisez-le pour votre équipe. 90% moins cher que de construire votre propre stack.",
    landing_hero_cta_trial: "Essai gratuit de 14 jours",
    landing_hero_cta_agency: "Tarifs agence",
    landing_hero_no_card: "Aucune carte requise · Annulation à tout moment · Installation en 2 minutes",
    landing_stat_agencies: "Agences utilisatrices",
    landing_stat_cheaper: "Moins cher que les alternatives",
    landing_stat_rating: "Note moyenne",
    landing_stat_whitelabel: "Prêt pour la marque blanche",
    landing_replaces: "REMPLACE TOUT CELA",
    landing_for_label: "CONÇU POUR DEUX TYPES D'ÉQUIPES",
    landing_for_h2: "Une plateforme. Deux cas d'usage puissants.",
    landing_for_sub: "Que vous gériez vos ventes en interne ou que vous revendiez un CRM à vos clients, ARGILETTE est fait pour vous.",
    landing_for_teams: "Équipes commerciales",
    landing_for_agencies_tab: "Agences & Revendeurs",
    landing_for_t1_title: "Gérez votre pipeline",
    landing_for_t1_desc: "CRM complet avec contacts, prospects, affaires et tableaux de pipeline visuels.",
    landing_for_t2_title: "L'IA fait le travail difficile",
    landing_for_t2_desc: "6 agents IA gèrent la prospection, la qualification et les relances en continu.",
    landing_for_t3_title: "Lancez des campagnes email",
    landing_for_t3_desc: "Envoyez des campagnes ciblées avec des analyses en temps réel des ouvertures, clics et réponses.",
    landing_for_t4_title: "Suivez chaque indicateur",
    landing_for_t4_desc: "Tableaux de bord revenus, rapports de performance d'équipe et prévisions de pipeline.",
    landing_for_a1_title: "Votre marque partout",
    landing_for_a1_desc: "Logo, couleurs, favicon, domaine — les clients ne voient jamais ARGILETTE.",
    landing_for_a2_title: "Espaces de travail isolés",
    landing_for_a2_desc: "Chaque client a son propre environnement sécurisé. Aucune fuite de données entre comptes.",
    landing_for_a3_title: "Gardez 100% de marge",
    landing_for_a3_desc: "Vous fixez votre prix. Nous vous facturons en gros. Vous gardez la différence.",
    landing_for_a4_title: "Domaines personnalisés",
    landing_for_a4_desc: "crm.votreclient.com avec SSL automatique. Configuration en quelques clics.",
    landing_feat_label: "FONCTIONNALITÉS",
    landing_feat_h2: "Tout ce qu'il faut pour conclure plus d'affaires",
    landing_feat_sub: "Remplacez 6 outils séparés par une plateforme unifiée et économisez des milliers par mois.",
    landing_feat_f1_title: "Gestion des contacts & prospects",
    landing_feat_f1_desc: "Centralisez chaque contact et prospect. Suivez toutes les interactions, scorez les prospects et transformez les conversations en revenus.",
    landing_feat_f2_title: "Pipeline de vente visuel",
    landing_feat_f2_desc: "Tableaux Kanban glisser-déposer avec 6 étapes personnalisables. Visualisez l'ensemble de votre pipeline d'un coup d'œil.",
    landing_feat_f3_title: "6 Employés IA",
    landing_feat_f3_desc: "Agents autonomes pour la prospection, le scoring, la gestion des réponses, la conclusion, la qualification des chats et la publication sociale.",
    landing_feat_f4_title: "Campagnes email",
    landing_feat_f4_desc: "Concevez, planifiez et envoyez des campagnes email et SMS ciblées depuis un tableau de bord unifié avec analyses en temps réel.",
    landing_feat_f5_title: "Analytique & Rapports",
    landing_feat_f5_desc: "Tableaux de bord en temps réel montrant les tendances de revenus, la performance d'équipe, le ROI des campagnes et la santé du pipeline.",
    landing_feat_f6_title: "Sécurité entreprise",
    landing_feat_f6_desc: "Isolation multi-tenant, contrôle d'accès basé sur les rôles, journaux d'audit et protection des données alignée SOC 2.",
    landing_ai_label: "EMPLOYÉS IA",
    landing_ai_h2_a: "6 agents IA qui travaillent",
    landing_ai_h2_b: "pendant votre sommeil",
    landing_ai_sub: "L'IA autonome gère l'intégralité de votre processus de vente — de la prospection à la conclusion. Chaque agent est conçu pour un objectif précis et apprend de vos données.",
    landing_ai_a1_name: "Prospecteur",
    landing_ai_a1_desc: "Trouve et qualifie de nouveaux prospects sur le web",
    landing_ai_a2_name: "Agent de prospection",
    landing_ai_a2_desc: "Rédige et envoie des emails froids personnalisés",
    landing_ai_a3_name: "Gestionnaire de réponses",
    landing_ai_a3_desc: "Répond aux prospects entrants en quelques minutes",
    landing_ai_a4_name: "Closer",
    landing_ai_a4_desc: "Élabore des propositions et des séquences de suivi",
    landing_ai_a5_name: "Qualificateur de chat",
    landing_ai_a5_desc: "Qualifie les visiteurs du site web en temps réel",
    landing_ai_a6_name: "Posteur social",
    landing_ai_a6_desc: "Publie du contenu sur vos réseaux sociaux",
    landing_wl_label: "MARQUE BLANCHE & AGENCE",
    landing_wl_h2_a: "Vendez-le comme le vôtre.",
    landing_wl_h2_b: "Gardez 100% des revenus.",
    landing_wl_sub: "Les agences et revendeurs apposent leur marque sur ARGILETTE. Logo, couleurs, domaine, emails — vos clients ne voient jamais notre nom.",
    landing_wl_f1_title: "Remplacement complet de la marque",
    landing_wl_f1_desc: "Votre logo, couleurs, favicon. Chaque pixel reflète votre marque — ARGILETTE est invisible pour vos clients.",
    landing_wl_f2_title: "Domaine personnalisé par client",
    landing_wl_f2_desc: "Pointez crm.votreclient.com vers leur espace. SSL provisionné automatiquement.",
    landing_wl_f3_title: "Emails transactionnels à votre marque",
    landing_wl_f3_desc: "Emails de bienvenue, d'invitation et de reçu envoyés depuis votre nom et domaine.",
    landing_wl_f4_title: "Espaces clients isolés",
    landing_wl_f4_desc: "Chaque client est dans son propre environnement sécurisé et isolé. Zéro fuite de données.",
    landing_wl_f5_title: "Vos prix, votre marge",
    landing_wl_f5_desc: "Nous vous facturons en gros. Vous fixez votre prix et gardez toute la différence.",
    landing_wl_f6_title: "Accès API & webhooks",
    landing_wl_f6_desc: "Connectez-vous à vos portails de facturation, tableaux de bord ou outils PSA existants.",
    landing_wl_without: "SANS MARQUE BLANCHE",
    landing_wl_with: "AVEC MARQUE BLANCHE",
    landing_wl_what_clients_see: "Ce que voient vos clients",
    landing_wl_bad1: "Logo ARGILETTE dans la barre latérale",
    landing_wl_bad2: "info@argilette.com dans les emails",
    landing_wl_bad3: "Mentions 'Propulsé par ARGILETTE'",
    landing_wl_bad4: "argilette.org dans le navigateur",
    landing_wl_good1: "Votre logo sur chaque page",
    landing_wl_good2: "Votre adresse email partout",
    landing_wl_good3: "Votre nom d'entreprise partout",
    landing_wl_good4: "crm.votredomaine.com avec SSL",
    landing_wl_existing: "Déjà client Business ou Entreprise ?",
    landing_wl_existing_desc: "La marque blanche est déjà incluse. Allez dans Paramètres → Marque blanche pour l'activer maintenant.",
    landing_test_label: "TÉMOIGNAGES",
    landing_test_h2: "Adoré par les équipes et les agences",
    landing_test_t1_text: "Nous avons migré depuis HubSpot et réduit nos coûts CRM de 70%. La génération d'emails par IA seule économise 3 heures par semaine par représentant.",
    landing_test_t1_name: "Sarah Mitchell",
    landing_test_t1_role: "Directrice Technique, TechVision Inc",
    landing_test_t2_text: "La configuration multi-tenant était parfaite pour notre agence. Chaque client a son propre espace isolé — entièrement sous notre marque.",
    landing_test_t2_name: "Marcus Johnson",
    landing_test_t2_role: "Directeur des Opérations, HealthBridge",
    landing_test_t3_text: "Nous revendons ceci à 14 clients à notre propre tarif. La marque blanche est transparente — aucun d'eux ne sait qu'ARGILETTE est derrière.",
    landing_test_t3_name: "Aisha Okonkwo",
    landing_test_t3_role: "PDG, GreenScale Digital",
    landing_price_label: "TARIFS",
    landing_price_h2: "Tarification transparente pour chaque cas d'usage",
    landing_price_sub: "Que vous soyez une équipe ou une agence, nous avons un plan pour vous.",
    landing_price_for_teams: "Pour les équipes",
    landing_price_for_agencies: "Pour les agences",
    landing_price_popular: "LE PLUS POPULAIRE",
    landing_price_footer: "Tous les plans incluent un essai gratuit de 14 jours · Aucune carte requise · Annulation à tout moment",
    landing_price_cta_trial: "Commencer l'essai gratuit",
    landing_price_cta_contact: "Contacter les ventes",
    landing_price_cta_start: "Commencer",
    landing_cta_h2: "Prêt à lancer votre propre CRM ?",
    landing_cta_sub: "Rejoignez plus de 3 400 agences et équipes commerciales. Commencez votre essai aujourd'hui — ou parlez-nous de la tarification marque blanche et agence.",
    landing_cta_trial: "Commencer l'essai gratuit",
    landing_cta_agency: "Parler à l'équipe commerciale",
    landing_cta_footer: "14 jours gratuits · Pas de carte · Annulation à tout moment",
    landing_footer_rights: "© 2026 ARGILETTE LLC. Tous droits réservés.",
    landing_footer_privacy: "Confidentialité",
    landing_footer_terms: "Conditions",
    landing_footer_security: "Sécurité",
  },
};

// ── Context ──────────────────────────────────────────────────────────────────
interface LanguageContextType {
  lang: string;
  setLang: (code: string) => void;
  t: (key: string, fallback?: string) => string;
  isRTL: boolean;
}

const LanguageContext = createContext<LanguageContextType>({
  lang: "en",
  setLang: () => {},
  t: (key, fallback) => fallback || key,
  isRTL: false,
});

const RTL_LANGS = ["ar", "he", "fa"];

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLangState] = useState<string>(() => {
    if (typeof localStorage !== "undefined") {
      return localStorage.getItem("preferred-language") || "en";
    }
    return "en";
  });

  const setLang = useCallback((code: string) => {
    setLangState(code);
    if (typeof localStorage !== "undefined") {
      localStorage.setItem("preferred-language", code);
    }
    // Apply RTL direction
    document.documentElement.dir = RTL_LANGS.includes(code) ? "rtl" : "ltr";
    document.documentElement.lang = code;
  }, []);

  useEffect(() => {
    document.documentElement.dir = RTL_LANGS.includes(lang) ? "rtl" : "ltr";
    document.documentElement.lang = lang;
  }, [lang]);

  const t = useCallback((key: string, fallback?: string): string => {
    const dict = translations[lang] || translations["en"];
    if (dict[key]) return dict[key];
    // Fall back to English
    if (lang !== "en" && translations["en"][key]) return translations["en"][key];
    return fallback || key;
  }, [lang]);

  const isRTL = RTL_LANGS.includes(lang);

  return (
    <LanguageContext.Provider value={{ lang, setLang, t, isRTL }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}

export { translations };
