/**
 * ARGILETTE Language Context — full French (and multi-language) i18n system
 * Usage: const { t, lang, setLang } = useLanguage();
 */
import React, { createContext, useContext, useState, useEffect, useCallback } from "react";

// ── Translation dictionary ──────────────────────────────────────────────────
const translations: Record<string, Record<string, string>> = {
  en: {
    // ── Navigation ──
    nav_crm: "CRM",
    nav_intelligence: "Intelligence",
    nav_sales_marketing: "Sales & Marketing",
    nav_platform: "Platform",
    nav_operations: "Operations",
    nav_admin: "Admin",

    nav_dashboard: "Dashboard",
    nav_contacts: "Contacts",
    nav_leads: "Leads",
    nav_deals: "Deals",
    nav_tasks: "Tasks",
    nav_accounts: "Accounts",
    nav_analytics: "Analytics",
    nav_ai_tools: "AI Tools",
    nav_automation: "Automation",
    nav_lead_intelligence: "Lead Intelligence",
    nav_ai_agents: "AI Agents",
    nav_skills_library: "Skills Library",
    nav_marketing_hub: "Marketing Hub",
    nav_campaigns: "Campaigns",
    nav_invoices: "Invoices",
    nav_seo_platform: "SEO Platform",
    nav_ecommerce: "E-commerce",
    nav_finance: "Finance",
    nav_projects: "Projects",
    nav_employees: "Employees",
    nav_team: "Team",
    nav_settings: "Settings",
    nav_code_healing: "Code Healing",

    // ── Global UI ──
    save: "Save",
    save_changes: "Save Changes",
    cancel: "Cancel",
    delete: "Delete",
    edit: "Edit",
    add: "Add",
    add_new: "Add New",
    search: "Search",
    filter: "Filter",
    sort: "Sort",
    loading: "Loading...",
    error: "Error",
    success: "Success",
    warning: "Warning",
    info: "Information",
    welcome: "Welcome",
    logout: "Log Out",
    profile: "Profile",
    confirm: "Confirm",
    close: "Close",
    view: "View",
    export: "Export",
    import: "Import",
    refresh: "Refresh",
    back: "Back",
    next: "Next",
    previous: "Previous",
    submit: "Submit",
    send: "Send",
    update: "Update",
    create: "Create",
    remove: "Remove",
    manage: "Manage",
    generate: "Generate",
    copy: "Copy",
    copied: "Copied!",
    open: "Open",
    continue: "Continue",
    actions: "Actions",
    status: "Status",
    date: "Date",
    name: "Name",
    email: "Email",
    phone: "Phone",
    company: "Company",
    notes: "Notes",
    type: "Type",
    amount: "Amount",
    total: "Total",
    active: "Active",
    inactive: "Inactive",
    pending: "Pending",
    completed: "Completed",
    cancelled: "Cancelled",
    draft: "Draft",
    published: "Published",
    none: "None",
    all: "All",
    yes: "Yes",
    no: "No",
    or: "or",
    and: "and",
    description: "Description",
    title: "Title",
    category: "Category",
    tags: "Tags",
    price: "Price",
    quantity: "Quantity",
    inventory: "Inventory",
    currency: "Currency",
    language: "Language",
    theme: "Theme",
    notifications: "Notifications",
    privacy: "Privacy",
    security: "Security",
    billing: "Billing",
    upgrade: "Upgrade",
    plan: "Plan",
    usage: "Usage",
    limit: "Limit",
    unlimited: "Unlimited",
    today: "Today",
    this_week: "This week",
    this_month: "This month",
    no_data: "No data available",
    try_again: "Try again",

    // ── Dashboard ──
    dashboard_title: "Dashboard",
    dashboard_subtitle: "Your business at a glance",
    total_contacts: "Total Contacts",
    total_leads: "Total Leads",
    total_deals: "Total Deals",
    total_revenue: "Total Revenue",
    recent_activity: "Recent Activity",
    quick_actions: "Quick Actions",
    add_contact: "Add Contact",
    add_lead: "Add Lead",
    add_deal: "Add Deal",
    add_task: "Add Task",
    pipeline_overview: "Pipeline Overview",
    top_deals: "Top Deals",
    tasks_due: "Tasks Due",
    conversion_rate: "Conversion Rate",
    win_rate: "Win Rate",
    avg_deal_size: "Avg. Deal Size",
    active_deals: "Active Deals",

    // ── Contacts ──
    contacts_title: "Contacts",
    contacts_subtitle: "Manage your contacts",
    add_contact_btn: "Add Contact",
    contact_name: "Full Name",
    contact_email: "Email Address",
    contact_phone: "Phone Number",
    contact_company: "Company",
    contact_position: "Job Title",
    contact_source: "Source",
    contact_status: "Status",
    contact_tags: "Tags",
    contact_notes: "Notes",
    import_contacts: "Import Contacts",
    export_contacts: "Export Contacts",
    no_contacts: "No contacts yet",
    no_contacts_desc: "Add your first contact to get started",
    search_contacts: "Search contacts...",
    edit_contact: "Edit Contact",
    delete_contact: "Delete Contact",
    contact_details: "Contact Details",
    linkedin_url: "LinkedIn Profile",
    location: "Location",
    website: "Website",
    employees: "Employees",

    // ── Leads ──
    leads_title: "Leads",
    leads_subtitle: "Track and convert leads",
    add_lead_btn: "Add Lead",
    lead_name: "Lead Name",
    lead_email: "Email",
    lead_company: "Company",
    lead_source: "Source",
    lead_status: "Status",
    lead_score: "Score",
    lead_value: "Value",
    lead_notes: "Notes",
    no_leads: "No leads yet",
    no_leads_desc: "Add your first lead to start filling your pipeline",
    edit_lead: "Edit Lead",
    delete_lead: "Delete Lead",
    convert_lead: "Convert to Contact",
    qualify_lead: "Qualify Lead",
    status_new: "New",
    status_contacted: "Contacted",
    status_qualified: "Qualified",
    status_lost: "Lost",
    status_converted: "Converted",
    search_leads: "Search leads...",

    // ── Deals ──
    deals_title: "Deals",
    deals_subtitle: "Manage your sales pipeline",
    add_deal_btn: "Add Deal",
    deal_name: "Deal Name",
    deal_value: "Deal Value",
    deal_stage: "Stage",
    deal_close_date: "Close Date",
    deal_contact: "Contact",
    deal_probability: "Probability",
    no_deals: "No deals yet",
    no_deals_desc: "Add your first deal to track your pipeline",
    pipeline: "Pipeline",
    stage_lead: "Lead",
    stage_prospect: "Prospect",
    stage_proposal: "Proposal",
    stage_negotiation: "Negotiation",
    stage_closed_won: "Closed Won",
    stage_closed_lost: "Closed Lost",

    // ── Tasks ──
    tasks_title: "Tasks",
    tasks_subtitle: "Manage your to-dos",
    add_task_btn: "Add Task",
    task_title: "Task Title",
    task_description: "Description",
    task_due_date: "Due Date",
    task_priority: "Priority",
    task_status: "Status",
    task_assigned: "Assigned To",
    no_tasks: "No tasks yet",
    no_tasks_desc: "Add your first task to stay organized",
    priority_low: "Low",
    priority_medium: "Medium",
    priority_high: "High",
    priority_urgent: "Urgent",
    due_today: "Due today",
    overdue: "Overdue",
    mark_complete: "Mark Complete",
    reopen: "Reopen",

    // ── Accounts ──
    accounts_title: "Accounts",
    accounts_subtitle: "Manage your company accounts",
    add_account_btn: "Add Account",
    account_name: "Company Name",
    account_industry: "Industry",
    account_size: "Company Size",
    account_website: "Website",
    account_revenue: "Annual Revenue",
    no_accounts: "No accounts yet",
    no_accounts_desc: "Add your first account to get started",

    // ── Analytics ──
    analytics_title: "Analytics",
    analytics_subtitle: "Insights and performance metrics",
    overview: "Overview",
    performance: "Performance",
    revenue_chart: "Revenue Chart",
    leads_chart: "Leads Over Time",
    conversion_funnel: "Conversion Funnel",
    top_sources: "Top Lead Sources",
    monthly_revenue: "Monthly Revenue",
    growth: "Growth",
    visitors: "Visitors",
    page_views: "Page Views",
    bounce_rate: "Bounce Rate",
    avg_session: "Avg. Session Duration",
    reports: "Reports",

    // ── AI Tools ──
    ai_tools_title: "AI Tools",
    ai_tools_subtitle: "Powered by Argilette AI",
    generate_content: "Generate Content",
    ai_writing: "AI Writing Assistant",
    email_templates: "Email Templates",
    seo_content: "SEO Content",
    social_media: "Social Media Posts",
    ad_copy: "Ad Copy",
    product_descriptions: "Product Descriptions",
    ai_analyze: "Analyze with AI",
    ai_suggest: "Get AI Suggestions",
    generating: "Generating...",
    tokens_used: "Tokens used",
    tokens_remaining: "Tokens remaining",

    // ── E-commerce ──
    ecommerce_title: "E-commerce",
    ecommerce_subtitle: "Manage your online stores",
    products_tab: "Products",
    orders_tab: "Orders",
    stores_tab: "Stores",
    inventory_tab: "Inventory",
    add_product: "Add Product",
    edit_product: "Edit Product",
    product_name: "Product Name",
    product_desc: "Description",
    product_price: "Price",
    compare_price: "Compare-at Price",
    product_sku: "SKU",
    product_category: "Category",
    product_inventory: "Inventory",
    product_images: "Images",
    product_tags: "Tags",
    featured_product: "Featured Product",
    available_sale: "Available for sale",
    track_inventory: "Track inventory",
    import_supplier: "Import from Supplier",
    supplier_url: "Supplier Website URL",
    no_products: "No products yet",
    no_products_desc: "Add your first product to start selling",
    total_stores: "Total Stores",
    total_products: "Total Products",
    total_orders: "Total Orders",
    total_revenue_ec: "Revenue",
    low_stock_alerts: "Low Stock Alerts",
    build_store: "Build Store with AI",
    visit_store: "Visit Store",
    store_name: "Store Name",
    store_domain: "Domain",
    store_settings: "Store Settings",
    stripe_public_key: "Stripe Publishable Key",
    stripe_secret_key: "Stripe Secret Key",
    logo_url: "Logo URL",
    banner_url: "Hero Banner URL",
    order_number: "Order #",
    customer: "Customer",
    order_status: "Status",
    payment_status: "Payment Status",
    order_date: "Date",
    out_of_stock: "Out of Stock",
    low_stock: "Low Stock",
    add_store: "Add Store",
    ai_build_store: "Build with AI",
    slug: "URL Slug",
    currency_ec: "Currency",
    is_published: "Published",
    products_count: "Products",
    orders_count: "Orders",
    revenue_ec: "Revenue",

    // ── Finance ──
    finance_title: "Finance",
    finance_subtitle: "Financial management",
    income: "Income",
    expenses: "Expenses",
    profit: "Profit",
    net_revenue: "Net Revenue",
    transactions: "Transactions",
    invoices_tab: "Invoices",
    payments: "Payments",
    tax: "Tax",
    bank_accounts: "Bank Accounts",

    // ── Marketing ──
    marketing_title: "Marketing Hub",
    marketing_subtitle: "Campaigns and outreach",
    campaigns_title: "Campaigns",
    campaigns_subtitle: "Manage marketing campaigns",
    create_campaign: "Create Campaign",
    campaign_name: "Campaign Name",
    campaign_type: "Type",
    campaign_status: "Status",
    campaign_budget: "Budget",
    campaign_audience: "Audience",
    send_email: "Send Email",
    send_sms: "Send SMS",
    email_campaign: "Email Campaign",
    sms_campaign: "SMS Campaign",
    social_campaign: "Social Campaign",
    no_campaigns: "No campaigns yet",

    // ── SEO ──
    seo_title: "SEO Platform",
    seo_subtitle: "Search engine optimization",
    keywords: "Keywords",
    keyword_research: "Keyword Research",
    site_audit: "Site Audit",
    backlinks: "Backlinks",
    rank_tracking: "Rank Tracking",
    competitor_analysis: "Competitor Analysis",
    content_intelligence: "Content Intelligence",
    local_seo: "Local SEO",
    seo_score: "SEO Score",
    search_volume: "Search Volume",
    difficulty: "Difficulty",
    position: "Position",
    impressions: "Impressions",
    clicks: "Clicks",

    // ── Projects ──
    projects_title: "Projects",
    projects_subtitle: "Project management",
    add_project: "Add Project",
    project_name: "Project Name",
    project_status: "Status",
    project_deadline: "Deadline",
    project_team: "Team",
    project_budget: "Budget",
    no_projects: "No projects yet",
    milestones: "Milestones",
    gantt_chart: "Gantt Chart",
    kanban: "Kanban Board",

    // ── Employees ──
    employees_title: "Employees",
    employees_subtitle: "HR management",
    add_employee: "Add Employee",
    employee_name: "Name",
    employee_position: "Position",
    employee_department: "Department",
    employee_email: "Email",
    employee_phone: "Phone",
    employee_status: "Status",
    no_employees: "No employees yet",
    department: "Department",
    hire_date: "Hire Date",
    salary: "Salary",

    // ── Team ──
    team_title: "Team",
    team_subtitle: "Manage team members and roles",
    team_members: "team members",
    invite_member: "Invite Member",
    member_name: "Name",
    member_email: "Email",
    member_role: "Role",
    member_status: "Status",
    no_members: "No team members yet",
    role_admin: "Admin",
    role_manager: "Manager",
    role_agent: "Agent",
    role_viewer: "Viewer",
    send_invite: "Send Invite",
    resend_invite: "Resend Invite",
    revoke_access: "Revoke Access",

    // ── Settings ──
    settings_title: "Settings",
    settings_subtitle: "Manage your account and preferences",
    profile_tab: "Profile",
    account_tab: "Account",
    notifications_tab: "Notifications",
    billing_tab: "Billing",
    security_tab: "Security",
    integrations_tab: "Integrations",
    language_tab: "Language",
    white_label_tab: "White Label",
    first_name: "First Name",
    last_name: "Last Name",
    email_address: "Email Address",
    phone_number: "Phone Number",
    timezone: "Timezone",
    change_password: "Change Password",
    current_password: "Current Password",
    new_password: "New Password",
    confirm_password: "Confirm Password",
    two_factor: "Two-Factor Authentication",
    choose_language: "Choose Language",
    language_saved: "Language preference saved",

    // ── Invoices ──
    invoices_title: "Invoices",
    invoices_subtitle: "Manage your invoices",
    create_invoice: "Create Invoice",
    invoice_number: "Invoice #",
    invoice_client: "Client",
    invoice_amount: "Amount",
    invoice_due: "Due Date",
    invoice_status: "Status",
    invoice_paid: "Paid",
    invoice_unpaid: "Unpaid",
    invoice_overdue: "Overdue",
    invoice_draft: "Draft",
    no_invoices: "No invoices yet",
    send_invoice: "Send Invoice",
    mark_paid: "Mark as Paid",
    download_pdf: "Download PDF",

    // ── Workflows / Automation ──
    workflows_title: "Automation",
    workflows_subtitle: "Automate your business processes",
    create_workflow: "Create Workflow",
    workflow_name: "Workflow Name",
    workflow_trigger: "Trigger",
    workflow_actions: "Actions",
    workflow_status: "Status",
    no_workflows: "No workflows yet",
    trigger_new_lead: "New Lead",
    trigger_new_contact: "New Contact",
    trigger_deal_stage: "Deal Stage Change",
    trigger_form: "Form Submission",
    action_send_email: "Send Email",
    action_create_task: "Create Task",
    action_notify: "Send Notification",
    action_update: "Update Record",

    // ── AI Agents ──
    agents_title: "AI Agents",
    agents_subtitle: "Autonomous AI workers",
    agent_social: "Social Author",
    agent_sdr: "SDR Outreach",
    agent_reply: "Reply Handler",
    agent_closer: "Deal Closer",
    agent_chatbot: "Chat Bot",
    agent_scorer: "Lead Scorer",
    agent_status_active: "Active",
    agent_status_idle: "Idle",
    agent_status_paused: "Paused",
    agent_tasks_today: "Tasks today",
    agent_configure: "Configure",
    agent_activate: "Activate",
    agent_pause: "Pause",
    agent_logs: "View Logs",

    // ── Intelligence ──
    intelligence_title: "Lead Intelligence",
    intelligence_subtitle: "AI-powered lead research",
    research_lead: "Research Lead",
    enrich_data: "Enrich Data",
    find_decision_makers: "Find Decision Makers",
    company_insights: "Company Insights",
    news_mentions: "News Mentions",
    social_presence: "Social Presence",
    ai_score: "AI Score",
    confidence: "Confidence",

    // ── Skills ──
    skills_title: "Skills Library",
    skills_subtitle: "AI-powered tools and templates",
    run_skill: "Run Skill",
    skill_category: "Category",
    skill_inputs: "Inputs",
    skill_output: "Output",
    no_skills: "No skills found",
    search_skills: "Search skills...",

    // ── Code Healing ──
    healing_title: "Code Healing",
    healing_subtitle: "Automated system diagnostics",
    last_scan: "Last Scan",
    issues_found: "Issues Found",
    issues_fixed: "Issues Fixed",
    run_scan: "Run Scan",
    scanning: "Scanning...",
    no_issues: "No issues found",
    system_health: "System Health",
    uptime: "Uptime",
    memory: "Memory",
    cpu: "CPU",
    database: "Database",

    // ── Storefront ──
    shop: "Shop",
    about: "About",
    contact: "Contact",
    add_to_cart: "Add to Cart",
    view_cart: "View Cart",
    checkout: "Checkout",
    your_cart: "Your Cart",
    cart_empty: "Your cart is empty",
    order_summary: "Order Summary",
    shipping: "Shipping",
    subtotal: "Subtotal",
    place_order: "Place Order",
    order_confirmed: "Order Confirmed",
    continue_shopping: "Continue Shopping",
    quick_view: "Quick View",
    featured: "Featured",
    in_stock: "In Stock",
    search_products: "Search products...",
    our_products: "Our Products",
    contact_shipping: "Contact & Shipping",
    full_name: "Full Name",
    email_address_sf: "Email",
    address: "Address",
    city: "City",
    state: "State",
    zip: "ZIP Code",
    country: "Country",
    phone_optional: "Phone (optional)",
    continue_payment: "Continue to Payment →",
    back_shipping: "← Back to shipping info",
    pay_now: "Pay",
    processing: "Processing...",
    manual_order: "Manual Order",
    trust_secure: "Secure Checkout",
    trust_shipping: "Fast Shipping",
    trust_quality: "Quality Guarantee",
    trust_support: "24/7 Support",
    items: "items",
    sort_default: "Sort: Default",
    sort_price_asc: "Price: Low → High",
    sort_price_desc: "Price: High → Low",
    sort_name: "Name A–Z",
    no_products_sf: "Products Coming Soon",
    no_products_sf_desc: "The store owner is adding products. Check back soon!",
    clear_search: "Clear Search",
    no_results: "No results found",
    try_different: "Try a different search term",
    message_sent: "Message Sent!",
    message_sent_desc: "We'll get back to you as soon as possible.",
    your_name: "Your Name",
    your_message: "Message",
    send_message: "Send Message →",
    powered_by: "Powered by",
    quick_links: "Quick Links",
    customer_service: "Customer Service",
    shipping_policy: "Shipping Policy",
    return_policy: "Return Policy",
    faq: "FAQ",
    all_rights: "All rights reserved",
    who_we_serve: "Who we serve",
    card_payment: "Card Payment",
    
    // ── Login / Register ──
    login_title: "Welcome back",
    login_subtitle: "Sign in to your account",
    email_label: "Email",
    password_label: "Password",
    sign_in: "Sign In",
    signing_in: "Signing in...",
    forgot_password: "Forgot password?",
    no_account: "Don't have an account?",
    start_trial: "Start free trial",
    register_title: "Create your account",
    register_subtitle: "Start your free trial today",
    sign_up: "Sign Up",
    already_account: "Already have an account?",
    sign_in_link: "Sign in",
    company_name_label: "Company Name",
    
    // ── Common status values ──
    status_active: "Active",
    status_inactive: "Inactive",
    status_pending: "Pending",
    status_completed: "Completed",
    status_cancelled: "Cancelled",
    status_draft: "Draft",
    status_paid: "Paid",
    status_overdue: "Overdue",
    status_processing: "Processing",
    status_shipped: "Shipped",
    status_delivered: "Delivered",
    status_open: "Open",
    status_won: "Won",
  },

  // ────────────────────────────────────────────────────────────────
  // FRENCH TRANSLATIONS
  // ────────────────────────────────────────────────────────────────
  fr: {
    // ── Navigation ──
    nav_crm: "CRM",
    nav_intelligence: "Intelligence",
    nav_sales_marketing: "Ventes & Marketing",
    nav_platform: "Plateforme",
    nav_operations: "Opérations",
    nav_admin: "Administration",

    nav_dashboard: "Tableau de bord",
    nav_contacts: "Contacts",
    nav_leads: "Prospects",
    nav_deals: "Affaires",
    nav_tasks: "Tâches",
    nav_accounts: "Comptes",
    nav_analytics: "Analytique",
    nav_ai_tools: "Outils IA",
    nav_automation: "Automatisation",
    nav_lead_intelligence: "Intelligence Prospects",
    nav_ai_agents: "Agents IA",
    nav_skills_library: "Bibliothèque de Compétences",
    nav_marketing_hub: "Hub Marketing",
    nav_campaigns: "Campagnes",
    nav_invoices: "Factures",
    nav_seo_platform: "Plateforme SEO",
    nav_ecommerce: "E-commerce",
    nav_finance: "Finance",
    nav_projects: "Projets",
    nav_employees: "Employés",
    nav_team: "Équipe",
    nav_settings: "Paramètres",
    nav_code_healing: "Autoréparation",

    // ── Global UI ──
    save: "Enregistrer",
    save_changes: "Enregistrer les modifications",
    cancel: "Annuler",
    delete: "Supprimer",
    edit: "Modifier",
    add: "Ajouter",
    add_new: "Ajouter",
    search: "Rechercher",
    filter: "Filtrer",
    sort: "Trier",
    loading: "Chargement...",
    error: "Erreur",
    success: "Succès",
    warning: "Avertissement",
    info: "Information",
    welcome: "Bienvenue",
    logout: "Déconnexion",
    profile: "Profil",
    confirm: "Confirmer",
    close: "Fermer",
    view: "Voir",
    export: "Exporter",
    import: "Importer",
    refresh: "Actualiser",
    back: "Retour",
    next: "Suivant",
    previous: "Précédent",
    submit: "Soumettre",
    send: "Envoyer",
    update: "Mettre à jour",
    create: "Créer",
    remove: "Retirer",
    manage: "Gérer",
    generate: "Générer",
    copy: "Copier",
    copied: "Copié !",
    open: "Ouvrir",
    continue: "Continuer",
    actions: "Actions",
    status: "Statut",
    date: "Date",
    name: "Nom",
    email: "E-mail",
    phone: "Téléphone",
    company: "Entreprise",
    notes: "Notes",
    type: "Type",
    amount: "Montant",
    total: "Total",
    active: "Actif",
    inactive: "Inactif",
    pending: "En attente",
    completed: "Terminé",
    cancelled: "Annulé",
    draft: "Brouillon",
    published: "Publié",
    none: "Aucun",
    all: "Tout",
    yes: "Oui",
    no: "Non",
    or: "ou",
    and: "et",
    description: "Description",
    title: "Titre",
    category: "Catégorie",
    tags: "Étiquettes",
    price: "Prix",
    quantity: "Quantité",
    inventory: "Inventaire",
    currency: "Devise",
    language: "Langue",
    theme: "Thème",
    notifications: "Notifications",
    privacy: "Confidentialité",
    security: "Sécurité",
    billing: "Facturation",
    upgrade: "Mise à niveau",
    plan: "Plan",
    usage: "Utilisation",
    limit: "Limite",
    unlimited: "Illimité",
    today: "Aujourd'hui",
    this_week: "Cette semaine",
    this_month: "Ce mois",
    no_data: "Aucune donnée disponible",
    try_again: "Réessayer",

    // ── Dashboard ──
    dashboard_title: "Tableau de bord",
    dashboard_subtitle: "Vue d'ensemble de votre activité",
    total_contacts: "Total Contacts",
    total_leads: "Total Prospects",
    total_deals: "Total Affaires",
    total_revenue: "Chiffre d'affaires",
    recent_activity: "Activité récente",
    quick_actions: "Actions rapides",
    add_contact: "Ajouter un contact",
    add_lead: "Ajouter un prospect",
    add_deal: "Ajouter une affaire",
    add_task: "Ajouter une tâche",
    pipeline_overview: "Aperçu du pipeline",
    top_deals: "Meilleures affaires",
    tasks_due: "Tâches à faire",
    conversion_rate: "Taux de conversion",
    win_rate: "Taux de réussite",
    avg_deal_size: "Valeur moyenne affaire",
    active_deals: "Affaires actives",

    // ── Contacts ──
    contacts_title: "Contacts",
    contacts_subtitle: "Gérer vos contacts",
    add_contact_btn: "Ajouter un contact",
    contact_name: "Nom complet",
    contact_email: "Adresse e-mail",
    contact_phone: "Numéro de téléphone",
    contact_company: "Entreprise",
    contact_position: "Poste",
    contact_source: "Source",
    contact_status: "Statut",
    contact_tags: "Étiquettes",
    contact_notes: "Notes",
    import_contacts: "Importer des contacts",
    export_contacts: "Exporter des contacts",
    no_contacts: "Aucun contact",
    no_contacts_desc: "Ajoutez votre premier contact pour commencer",
    search_contacts: "Rechercher des contacts...",
    edit_contact: "Modifier le contact",
    delete_contact: "Supprimer le contact",
    contact_details: "Détails du contact",
    linkedin_url: "Profil LinkedIn",
    location: "Localisation",
    website: "Site web",
    employees: "Employés",

    // ── Leads ──
    leads_title: "Prospects",
    leads_subtitle: "Suivre et convertir les prospects",
    add_lead_btn: "Ajouter un prospect",
    lead_name: "Nom du prospect",
    lead_email: "E-mail",
    lead_company: "Entreprise",
    lead_source: "Source",
    lead_status: "Statut",
    lead_score: "Score",
    lead_value: "Valeur",
    lead_notes: "Notes",
    no_leads: "Aucun prospect",
    no_leads_desc: "Ajoutez votre premier prospect pour remplir votre pipeline",
    edit_lead: "Modifier le prospect",
    delete_lead: "Supprimer le prospect",
    convert_lead: "Convertir en contact",
    qualify_lead: "Qualifier le prospect",
    status_new: "Nouveau",
    status_contacted: "Contacté",
    status_qualified: "Qualifié",
    status_lost: "Perdu",
    status_converted: "Converti",
    search_leads: "Rechercher des prospects...",

    // ── Deals ──
    deals_title: "Affaires",
    deals_subtitle: "Gérer votre pipeline commercial",
    add_deal_btn: "Ajouter une affaire",
    deal_name: "Nom de l'affaire",
    deal_value: "Valeur",
    deal_stage: "Étape",
    deal_close_date: "Date de clôture",
    deal_contact: "Contact",
    deal_probability: "Probabilité",
    no_deals: "Aucune affaire",
    no_deals_desc: "Ajoutez votre première affaire pour suivre votre pipeline",
    pipeline: "Pipeline",
    stage_lead: "Prospect",
    stage_prospect: "Intérêt",
    stage_proposal: "Proposition",
    stage_negotiation: "Négociation",
    stage_closed_won: "Gagné",
    stage_closed_lost: "Perdu",

    // ── Tasks ──
    tasks_title: "Tâches",
    tasks_subtitle: "Gérer vos tâches",
    add_task_btn: "Ajouter une tâche",
    task_title: "Titre de la tâche",
    task_description: "Description",
    task_due_date: "Date d'échéance",
    task_priority: "Priorité",
    task_status: "Statut",
    task_assigned: "Assigné à",
    no_tasks: "Aucune tâche",
    no_tasks_desc: "Ajoutez votre première tâche pour rester organisé",
    priority_low: "Faible",
    priority_medium: "Moyenne",
    priority_high: "Élevée",
    priority_urgent: "Urgent",
    due_today: "À rendre aujourd'hui",
    overdue: "En retard",
    mark_complete: "Marquer comme terminé",
    reopen: "Rouvrir",

    // ── Accounts ──
    accounts_title: "Comptes",
    accounts_subtitle: "Gérer vos comptes entreprises",
    add_account_btn: "Ajouter un compte",
    account_name: "Nom de l'entreprise",
    account_industry: "Secteur",
    account_size: "Taille",
    account_website: "Site web",
    account_revenue: "Chiffre d'affaires annuel",
    no_accounts: "Aucun compte",
    no_accounts_desc: "Ajoutez votre premier compte pour commencer",

    // ── Analytics ──
    analytics_title: "Analytique",
    analytics_subtitle: "Informations et indicateurs de performance",
    overview: "Vue d'ensemble",
    performance: "Performance",
    revenue_chart: "Graphique des revenus",
    leads_chart: "Prospects dans le temps",
    conversion_funnel: "Entonnoir de conversion",
    top_sources: "Meilleures sources de prospects",
    monthly_revenue: "Revenus mensuels",
    growth: "Croissance",
    visitors: "Visiteurs",
    page_views: "Pages vues",
    bounce_rate: "Taux de rebond",
    avg_session: "Durée moyenne de session",
    reports: "Rapports",

    // ── AI Tools ──
    ai_tools_title: "Outils IA",
    ai_tools_subtitle: "Propulsé par Argilette IA",
    generate_content: "Générer du contenu",
    ai_writing: "Assistant rédaction IA",
    email_templates: "Modèles d'e-mail",
    seo_content: "Contenu SEO",
    social_media: "Publications réseaux sociaux",
    ad_copy: "Texte publicitaire",
    product_descriptions: "Descriptions produits",
    ai_analyze: "Analyser avec l'IA",
    ai_suggest: "Suggestions IA",
    generating: "Génération en cours...",
    tokens_used: "Jetons utilisés",
    tokens_remaining: "Jetons restants",

    // ── E-commerce ──
    ecommerce_title: "E-commerce",
    ecommerce_subtitle: "Gérez vos boutiques en ligne",
    products_tab: "Produits",
    orders_tab: "Commandes",
    stores_tab: "Boutiques",
    inventory_tab: "Inventaire",
    add_product: "Ajouter un produit",
    edit_product: "Modifier le produit",
    product_name: "Nom du produit",
    product_desc: "Description",
    product_price: "Prix",
    compare_price: "Prix barré",
    product_sku: "Référence",
    product_category: "Catégorie",
    product_inventory: "Inventaire",
    product_images: "Images",
    product_tags: "Étiquettes",
    featured_product: "Produit vedette",
    available_sale: "Disponible à la vente",
    track_inventory: "Suivre l'inventaire",
    import_supplier: "Importer du fournisseur",
    supplier_url: "URL du site fournisseur",
    no_products: "Aucun produit",
    no_products_desc: "Ajoutez votre premier produit pour commencer à vendre",
    total_stores: "Boutiques",
    total_products: "Produits",
    total_orders: "Commandes",
    total_revenue_ec: "Revenus",
    low_stock_alerts: "Alertes stock faible",
    build_store: "Créer une boutique avec l'IA",
    visit_store: "Visiter la boutique",
    store_name: "Nom de la boutique",
    store_domain: "Domaine",
    store_settings: "Paramètres de la boutique",
    stripe_public_key: "Clé publique Stripe",
    stripe_secret_key: "Clé secrète Stripe",
    logo_url: "URL du logo",
    banner_url: "URL de la bannière",
    order_number: "Commande n°",
    customer: "Client",
    order_status: "Statut",
    payment_status: "Paiement",
    order_date: "Date",
    out_of_stock: "Rupture de stock",
    low_stock: "Stock faible",
    add_store: "Ajouter une boutique",
    ai_build_store: "Créer avec l'IA",
    slug: "Identifiant URL",
    currency_ec: "Devise",
    is_published: "Publié",
    products_count: "Produits",
    orders_count: "Commandes",
    revenue_ec: "Revenus",

    // ── Finance ──
    finance_title: "Finance",
    finance_subtitle: "Gestion financière",
    income: "Revenus",
    expenses: "Dépenses",
    profit: "Profit",
    net_revenue: "Revenu net",
    transactions: "Transactions",
    invoices_tab: "Factures",
    payments: "Paiements",
    tax: "Taxe",
    bank_accounts: "Comptes bancaires",

    // ── Marketing ──
    marketing_title: "Hub Marketing",
    marketing_subtitle: "Campagnes et communication",
    campaigns_title: "Campagnes",
    campaigns_subtitle: "Gérer les campagnes marketing",
    create_campaign: "Créer une campagne",
    campaign_name: "Nom de la campagne",
    campaign_type: "Type",
    campaign_status: "Statut",
    campaign_budget: "Budget",
    campaign_audience: "Audience",
    send_email: "Envoyer un e-mail",
    send_sms: "Envoyer un SMS",
    email_campaign: "Campagne e-mail",
    sms_campaign: "Campagne SMS",
    social_campaign: "Campagne sociale",
    no_campaigns: "Aucune campagne",

    // ── SEO ──
    seo_title: "Plateforme SEO",
    seo_subtitle: "Optimisation pour les moteurs de recherche",
    keywords: "Mots-clés",
    keyword_research: "Recherche de mots-clés",
    site_audit: "Audit du site",
    backlinks: "Liens entrants",
    rank_tracking: "Suivi des positions",
    competitor_analysis: "Analyse concurrentielle",
    content_intelligence: "Intelligence de contenu",
    local_seo: "SEO local",
    seo_score: "Score SEO",
    search_volume: "Volume de recherche",
    difficulty: "Difficulté",
    position: "Position",
    impressions: "Impressions",
    clicks: "Clics",

    // ── Projects ──
    projects_title: "Projets",
    projects_subtitle: "Gestion de projets",
    add_project: "Ajouter un projet",
    project_name: "Nom du projet",
    project_status: "Statut",
    project_deadline: "Échéance",
    project_team: "Équipe",
    project_budget: "Budget",
    no_projects: "Aucun projet",
    milestones: "Jalons",
    gantt_chart: "Diagramme de Gantt",
    kanban: "Tableau Kanban",

    // ── Employees ──
    employees_title: "Employés",
    employees_subtitle: "Gestion des ressources humaines",
    add_employee: "Ajouter un employé",
    employee_name: "Nom",
    employee_position: "Poste",
    employee_department: "Département",
    employee_email: "E-mail",
    employee_phone: "Téléphone",
    employee_status: "Statut",
    no_employees: "Aucun employé",
    department: "Département",
    hire_date: "Date d'embauche",
    salary: "Salaire",

    // ── Team ──
    team_title: "Équipe",
    team_subtitle: "Gérer les membres et les rôles",
    team_members: "membres",
    invite_member: "Inviter un membre",
    member_name: "Nom",
    member_email: "E-mail",
    member_role: "Rôle",
    member_status: "Statut",
    no_members: "Aucun membre",
    role_admin: "Administrateur",
    role_manager: "Responsable",
    role_agent: "Agent",
    role_viewer: "Observateur",
    send_invite: "Envoyer l'invitation",
    resend_invite: "Renvoyer l'invitation",
    revoke_access: "Révoquer l'accès",

    // ── Settings ──
    settings_title: "Paramètres",
    settings_subtitle: "Gérer votre compte et vos préférences",
    profile_tab: "Profil",
    account_tab: "Compte",
    notifications_tab: "Notifications",
    billing_tab: "Facturation",
    security_tab: "Sécurité",
    integrations_tab: "Intégrations",
    language_tab: "Langue",
    white_label_tab: "Marque blanche",
    first_name: "Prénom",
    last_name: "Nom de famille",
    email_address: "Adresse e-mail",
    phone_number: "Numéro de téléphone",
    timezone: "Fuseau horaire",
    change_password: "Changer le mot de passe",
    current_password: "Mot de passe actuel",
    new_password: "Nouveau mot de passe",
    confirm_password: "Confirmer le mot de passe",
    two_factor: "Authentification à deux facteurs",
    choose_language: "Choisir la langue",
    language_saved: "Préférence de langue enregistrée",

    // ── Invoices ──
    invoices_title: "Factures",
    invoices_subtitle: "Gérer vos factures",
    create_invoice: "Créer une facture",
    invoice_number: "Facture n°",
    invoice_client: "Client",
    invoice_amount: "Montant",
    invoice_due: "Date d'échéance",
    invoice_status: "Statut",
    invoice_paid: "Payée",
    invoice_unpaid: "Impayée",
    invoice_overdue: "En retard",
    invoice_draft: "Brouillon",
    no_invoices: "Aucune facture",
    send_invoice: "Envoyer la facture",
    mark_paid: "Marquer comme payée",
    download_pdf: "Télécharger le PDF",

    // ── Workflows ──
    workflows_title: "Automatisation",
    workflows_subtitle: "Automatisez vos processus métier",
    create_workflow: "Créer un workflow",
    workflow_name: "Nom du workflow",
    workflow_trigger: "Déclencheur",
    workflow_actions: "Actions",
    workflow_status: "Statut",
    no_workflows: "Aucun workflow",
    trigger_new_lead: "Nouveau prospect",
    trigger_new_contact: "Nouveau contact",
    trigger_deal_stage: "Changement d'étape",
    trigger_form: "Soumission de formulaire",
    action_send_email: "Envoyer un e-mail",
    action_create_task: "Créer une tâche",
    action_notify: "Envoyer une notification",
    action_update: "Mettre à jour l'enregistrement",

    // ── AI Agents ──
    agents_title: "Agents IA",
    agents_subtitle: "Travailleurs IA autonomes",
    agent_social: "Auteur Social",
    agent_sdr: "Prospection SDR",
    agent_reply: "Gestionnaire de réponses",
    agent_closer: "Closeur d'affaires",
    agent_chatbot: "Bot de chat",
    agent_scorer: "Scoreur de prospects",
    agent_status_active: "Actif",
    agent_status_idle: "Inactif",
    agent_status_paused: "En pause",
    agent_tasks_today: "Tâches aujourd'hui",
    agent_configure: "Configurer",
    agent_activate: "Activer",
    agent_pause: "Mettre en pause",
    agent_logs: "Voir les journaux",

    // ── Intelligence ──
    intelligence_title: "Intelligence Prospects",
    intelligence_subtitle: "Recherche de prospects assistée par IA",
    research_lead: "Rechercher le prospect",
    enrich_data: "Enrichir les données",
    find_decision_makers: "Trouver les décideurs",
    company_insights: "Informations sur l'entreprise",
    news_mentions: "Mentions dans les actualités",
    social_presence: "Présence sociale",
    ai_score: "Score IA",
    confidence: "Confiance",

    // ── Skills ──
    skills_title: "Bibliothèque de Compétences",
    skills_subtitle: "Outils et modèles assistés par IA",
    run_skill: "Exécuter",
    skill_category: "Catégorie",
    skill_inputs: "Entrées",
    skill_output: "Résultat",
    no_skills: "Aucune compétence trouvée",
    search_skills: "Rechercher des compétences...",

    // ── Code Healing ──
    healing_title: "Autoréparation du code",
    healing_subtitle: "Diagnostics système automatisés",
    last_scan: "Dernier scan",
    issues_found: "Problèmes détectés",
    issues_fixed: "Problèmes corrigés",
    run_scan: "Lancer le scan",
    scanning: "Scan en cours...",
    no_issues: "Aucun problème détecté",
    system_health: "Santé du système",
    uptime: "Disponibilité",
    memory: "Mémoire",
    cpu: "CPU",
    database: "Base de données",

    // ── Storefront ──
    shop: "Boutique",
    about: "À propos",
    contact: "Contact",
    add_to_cart: "Ajouter au panier",
    view_cart: "Voir le panier",
    checkout: "Passer la commande",
    your_cart: "Votre panier",
    cart_empty: "Votre panier est vide",
    order_summary: "Résumé de la commande",
    shipping: "Livraison",
    subtotal: "Sous-total",
    place_order: "Passer la commande",
    order_confirmed: "Commande confirmée !",
    continue_shopping: "Continuer mes achats",
    quick_view: "Aperçu rapide",
    featured: "Vedette",
    in_stock: "En stock",
    search_products: "Rechercher des produits...",
    our_products: "Nos Produits",
    contact_shipping: "Contact & Livraison",
    full_name: "Nom complet",
    email_address_sf: "E-mail",
    address: "Adresse",
    city: "Ville",
    state: "Région",
    zip: "Code postal",
    country: "Pays",
    phone_optional: "Téléphone (facultatif)",
    continue_payment: "Continuer vers le paiement →",
    back_shipping: "← Retour aux informations de livraison",
    pay_now: "Payer",
    processing: "Traitement en cours...",
    manual_order: "Commande manuelle",
    trust_secure: "Paiement sécurisé",
    trust_shipping: "Livraison rapide",
    trust_quality: "Garantie qualité",
    trust_support: "Support 24h/24",
    items: "articles",
    sort_default: "Tri : Par défaut",
    sort_price_asc: "Prix : Croissant",
    sort_price_desc: "Prix : Décroissant",
    sort_name: "Nom A–Z",
    no_products_sf: "Produits bientôt disponibles",
    no_products_sf_desc: "Le propriétaire de la boutique ajoute des produits. Revenez bientôt !",
    clear_search: "Effacer la recherche",
    no_results: "Aucun résultat",
    try_different: "Essayez un terme de recherche différent",
    message_sent: "Message envoyé !",
    message_sent_desc: "Nous vous répondrons dès que possible.",
    your_name: "Votre nom",
    your_message: "Message",
    send_message: "Envoyer le message →",
    powered_by: "Propulsé par",
    quick_links: "Liens rapides",
    customer_service: "Service client",
    shipping_policy: "Politique de livraison",
    return_policy: "Politique de retour",
    faq: "FAQ",
    all_rights: "Tous droits réservés",
    who_we_serve: "Qui nous servons",
    card_payment: "Paiement par carte",

    // ── Login / Register ──
    login_title: "Bon retour",
    login_subtitle: "Connectez-vous à votre compte",
    email_label: "E-mail",
    password_label: "Mot de passe",
    sign_in: "Se connecter",
    signing_in: "Connexion en cours...",
    forgot_password: "Mot de passe oublié ?",
    no_account: "Vous n'avez pas de compte ?",
    start_trial: "Commencer l'essai gratuit",
    register_title: "Créer votre compte",
    register_subtitle: "Commencez votre essai gratuit aujourd'hui",
    sign_up: "S'inscrire",
    already_account: "Vous avez déjà un compte ?",
    sign_in_link: "Se connecter",
    company_name_label: "Nom de l'entreprise",

    // ── Common status values ──
    status_active: "Actif",
    status_inactive: "Inactif",
    status_pending: "En attente",
    status_completed: "Terminé",
    status_cancelled: "Annulé",
    status_draft: "Brouillon",
    status_paid: "Payé",
    status_overdue: "En retard",
    status_processing: "En traitement",
    status_shipped: "Expédié",
    status_delivered: "Livré",
    status_open: "Ouvert",
    status_won: "Gagné",
  },
};

// ── Context ──────────────────────────────────────────────────────────────────
interface LanguageContextType {
  lang: string;
  setLang: (code: string) => void;
  t: (key: string, fallback?: string) => string;
  isRTL: boolean;
}

const LanguageContext = createContext<LanguageContextType>({
  lang: "en",
  setLang: () => {},
  t: (key, fallback) => fallback || key,
  isRTL: false,
});

const RTL_LANGS = ["ar", "he", "fa"];

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLangState] = useState<string>(() => {
    if (typeof localStorage !== "undefined") {
      return localStorage.getItem("preferred-language") || "en";
    }
    return "en";
  });

  const setLang = useCallback((code: string) => {
    setLangState(code);
    if (typeof localStorage !== "undefined") {
      localStorage.setItem("preferred-language", code);
    }
    // Apply RTL direction
    document.documentElement.dir = RTL_LANGS.includes(code) ? "rtl" : "ltr";
    document.documentElement.lang = code;
  }, []);

  useEffect(() => {
    document.documentElement.dir = RTL_LANGS.includes(lang) ? "rtl" : "ltr";
    document.documentElement.lang = lang;
  }, [lang]);

  const t = useCallback((key: string, fallback?: string): string => {
    const dict = translations[lang] || translations["en"];
    if (dict[key]) return dict[key];
    // Fall back to English
    if (lang !== "en" && translations["en"][key]) return translations["en"][key];
    return fallback || key;
  }, [lang]);

  const isRTL = RTL_LANGS.includes(lang);

  return (
    <LanguageContext.Provider value={{ lang, setLang, t, isRTL }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}

export { translations };
